"""Add trial outcome and link formal contract to trial

Revision ID: 008ee2c5556f
Revises: a7603fdc279e
Create Date: 2025-09-04 10:55:46.938839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008ee2c5556f'
down_revision = 'a7603fdc279e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 手动创建 ENUM 类型，这是关键修复
    op.execute("CREATE TYPE trialoutcome AS ENUM ('PENDING', 'SUCCESS', 'FAILURE')")

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_trial_contract_id', sa.UUID(),nullable=True, comment='关联的源试工合同ID'))
        # 添加列时，告诉 SQLAlchemy 不要再尝试创建类型，因为我们已经手动创建了
        batch_op.add_column(sa.Column('trial_outcome', sa.Enum('PENDING','SUCCESS', 'FAILURE', name='trialoutcome', create_type=False), server_default='PENDING', nullable=False, comment='试工结果 (pending, success, failure)'))
        batch_op.create_index(batch_op.f('ix_contracts_source_trial_contract_id'), ['source_trial_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_trial_outcome'), ['trial_outcome'], unique=False)
        # 在 Alembic 2.x 和 SQLAlchemy 1.4+ 中，外键约束的命名通常由 Alembic 自动处理，
        # 如果之前的 create_foreign_key(None, ...) 导致问题，可以尝试指定一个名称，或者让 Alembic 自动处理。
        # 为清晰起见，我们保持 Alembic 的默认行为。
        batch_op.create_foreign_key('fk_contracts_source_trial_contract_id','contracts', ['source_trial_contract_id'], ['id'], ondelete='SET NULL')

    # 下面这部分 exampapercourse 的修改与我们的任务无关，但它在原始脚本中，所以保留它
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        # 这里的约束名可能需要根据你的实际情况调整，如果再次报错的话
        # 但通常 Alembic 会处理好
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_exampapercourse_course_id_trainingcourse'), 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_exampapercourse_exam_paper_id_exampaper'), 'exampaper', ['exam_paper_id'],['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 与 upgrade 相反，先处理 exampapercourse
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_exampapercourse_exam_paper_id_exampaper'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_exampapercourse_course_id_trainingcourse'), type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey','trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey','exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # 然后处理 contracts 表
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contracts_source_trial_contract_id',type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_trial_outcome'))
        batch_op.drop_index(batch_op.f('ix_contracts_source_trial_contract_id'))
        batch_op.drop_column('trial_outcome')
        batch_op.drop_column('source_trial_contract_id')

    # 最后，手动删除 ENUM 类型
    op.execute("DROP TYPE trialoutcome")

    # ### end Alembic commands ###