"""Add FormFolder model and folder_id to DynamicForm

Revision ID: 00bcb64c4283
Revises: 6ddb22b8c22d
Create Date: 2025-11-19 15:25:14.800904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00bcb64c4283'
down_revision = '6ddb22b8c22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_folder',
    sa.Column('id', sa.UUID(), nullable=False, comment='文件夹ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='文件夹名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='文件夹描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='表单文件夹表'
    )
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.UUID(), nullable=True, comment='所属文件夹ID'))
        batch_op.create_foreign_key(None, 'form_folder', ['folder_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('folder_id')

    op.drop_table('form_folder')
    # ### end Alembic commands ###
