"""manual_ alembic_ add_ course_ resource

Revision ID: 01a2c6fb43e7
Revises: 9c1e9bb0434c
Create Date: 2025-05-20 13:17:04.164670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a2c6fb43e7'
down_revision = '9c1e9bb0434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_resource',
    sa.Column('id', sa.UUID(), nullable=False, comment='资源ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='资源原始文件名或显示名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='资源描述'),
    sa.Column('file_path', sa.String(length=1024), nullable=False, comment='文件在服务器上的存储路径或云存储的key'),
    sa.Column('file_type', sa.String(length=50), nullable=False, comment='文件主类型 (video, audio, document)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型 (e.g., video/mp4)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='文件大小 (字节)'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='音视频时长 (秒)'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='所属课程ID'),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True, comment='上传用户ID'),
    sa.Column('play_count', sa.Integer(), server_default='0', nullable=False, comment='播放次数'),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False, comment='资源在课程内的显示顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['course_id'], ['trainingcourse.id'], name='fk_courseresource_course_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['user.id'], name='fk_courseresource_uploader_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程的媒体和文档资源表'
    )
    op.create_index(op.f('ix_course_resource_course_id'), 'course_resource', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_resource_uploaded_by_user_id'), 'course_resource', ['uploaded_by_user_id'], unique=False)
    op.create_table('user_resource_play_log',
    sa.Column('id', sa.UUID(), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='资源ID'),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='播放时间'),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=True, comment='本次观看时长 (秒)'),
    sa.Column('percentage_watched', sa.Float(), nullable=True, comment='本次观看百分比'),
    sa.ForeignKeyConstraint(['resource_id'], ['course_resource.id'], name='fk_userresourceplaylog_resource_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userresourceplaylog_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户资源播放日志表'
    )
    op.create_index(op.f('ix_user_resource_play_log_resource_id'), 'user_resource_play_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_user_resource_play_log_user_id'), 'user_resource_play_log', ['user_id'], unique=False)
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_resource_play_log_user_id'), table_name='user_resource_play_log')
    op.drop_index(op.f('ix_user_resource_play_log_resource_id'), table_name='user_resource_play_log')
    op.drop_table('user_resource_play_log')
    op.drop_index(op.f('ix_course_resource_uploaded_by_user_id'), table_name='course_resource')
    op.drop_index(op.f('ix_course_resource_course_id'), table_name='course_resource')
    op.drop_table('course_resource')
    # ### end Alembic commands ###
