"""add_attendance_form_and_update_record

Revision ID: 01c30148b61c
Revises: bbae06f7a92d
Create Date: 2025-12-03 13:30:34.377018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '01c30148b61c'
down_revision = 'bbae06f7a92d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='关联合同ID'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='员工ID'),
    sa.Column('cycle_start_date', sa.DateTime(timezone=True), nullable=False, comment='考勤周期开始日期'),
    sa.Column('cycle_end_date', sa.DateTime(timezone=True), nullable=False, comment='考勤周期结束日期'),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='考勤表单数据,包含休息、请假、加班、出京、出境、带薪休假等所有明细'),
    sa.Column('employee_access_token', sa.String(length=255), nullable=True, comment='员工访问令牌,用于生成固定链接'),
    sa.Column('customer_signature_token', sa.String(length=255), nullable=True, comment='客户签署令牌,用于生成签署链接'),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False, comment='状态: draft, employee_confirmed, customer_signed, synced'),
    sa.Column('customer_signed_at', sa.DateTime(timezone=True), nullable=True, comment='客户签署时间'),
    sa.Column('signature_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='签署记录,包含签署人、时间、IP等信息'),
    sa.Column('synced_to_attendance', sa.Boolean(), server_default='false', nullable=False, comment='是否已同步到AttendanceRecord'),
    sa.Column('attendance_record_id', sa.UUID(), nullable=True, comment='关联的AttendanceRecord ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendance_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'cycle_start_date', name='uq_contract_cycle'),
    comment='电子考勤表'
    )
    with op.batch_alter_table('attendance_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_forms_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_forms_customer_signature_token'), ['customer_signature_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_forms_employee_access_token'), ['employee_access_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_attendance_forms_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_forms_status'), ['status'], unique=False)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_beijing_days', sa.Numeric(precision=10, scale=3), nullable=True, comment='出京天数(精确到0.001天)'))
        batch_op.add_column(sa.Column('out_of_country_days', sa.Numeric(precision=10, scale=3), nullable=True, comment='出境天数(精确到0.001天)'))
        batch_op.add_column(sa.Column('attendance_form_id', sa.UUID(), nullable=True, comment='关联的电子考勤表ID'))
        batch_op.add_column(sa.Column('attendance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='详细考勤数据,包含带薪休假等明细(仅用于显示)'))
        batch_op.create_foreign_key(None, 'attendance_forms', ['attendance_form_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('dynamic_form_data', schema=None) as batch_op:
        batch_op.alter_column('contract_id',
               existing_type=sa.UUID(),
               comment='关联的合同ID (如果适用，例如下户总结)',
               existing_comment='关联的合同ID',
               existing_nullable=True)
        batch_op.drop_index('idx_dynamic_form_data_contract_id')
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dynamic_form_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_dynamic_form_data_contract_id', ['contract_id'], unique=False)
        batch_op.alter_column('contract_id',
               existing_type=sa.UUID(),
               comment='关联的合同ID',
               existing_comment='关联的合同ID (如果适用，例如下户总结)',
               existing_nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('attendance_details')
        batch_op.drop_column('attendance_form_id')
        batch_op.drop_column('out_of_country_days')
        batch_op.drop_column('out_of_beijing_days')

    with op.batch_alter_table('attendance_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_forms_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_forms_employee_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_forms_employee_access_token'))
        batch_op.drop_index(batch_op.f('ix_attendance_forms_customer_signature_token'))
        batch_op.drop_index(batch_op.f('ix_attendance_forms_contract_id'))

    op.drop_table('attendance_forms')
    # ### end Alembic commands ###
