"""add mirrored_adjustment to financial_adjustment

Revision ID: 0240259fda98
Revises: 25ce1f3a7ee3
Create Date: 2025-10-28 10:19:00.585690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0240259fda98'
down_revision = '25ce1f3a7ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mirrored_adjustment_id', sa.UUID(), nullable=True, comment='关联的镜像财务调整项ID'))
        batch_op.create_index(batch_op.f('ix_financial_adjustments_mirrored_adjustment_id'), ['mirrored_adjustment_id'], unique=False)
        batch_op.create_foreign_key(None, 'financial_adjustments', ['mirrored_adjustment_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financial_adjustments_mirrored_adjustment_id'))
        batch_op.drop_column('mirrored_adjustment_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
