"""integrate_formal_contract_into_base_contract

Revision ID: 027153410068
Revises: 47cf12b8e356
Create Date: 2025-11-05 16:47:43.855050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '027153410068'
down_revision = '47cf12b8e356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))

        # --- 手动添加的字段 ---
        batch_op.add_column(sa.Column('template_id', sa.UUID(), nullable=True, comment= '关联的合同模板ID'))
        batch_op.add_column(sa.Column('service_content', JSONB(), nullable=True, comment='服务内容 (JSON 数组)')) # 注意这里是 JSONB()
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=True, comment='服务方式 (e.g., 全日住家型)'))
        batch_op.add_column(sa.Column('attachment_content', sa.Text(), nullable=True, comment= '附件内容 (Markdown 格式)'))
        batch_op.add_column(sa.Column('signing_status', sa.Enum('UNSIGNED', 'SIGNED', 'PENDING', 'CUSTOMER_SIGNED', 'EMPLOYEE_SIGNED', 'ACTIVE', 'TERMINATED', 'EXPIRED', name='signingstatus'), nullable=True, server_default=sa.text("'unsigned'"), comment='签署状态'))
        batch_op.add_column(sa.Column('customer_signature', sa.String(length=512), nullable=True, comment='甲方签名图片URL或Base64数据'))
        batch_op.add_column(sa.Column('employee_signature', sa.String(length=512), nullable=True, comment='乙方签名图片URL或Base64数据'))
        batch_op.add_column(sa.Column('unique_signing_token', sa.String(length=255), nullable= True, comment='唯一签署链接令牌'))
        batch_op.add_column(sa.Column('previous_contract_id', sa.UUID(), nullable=True, comment= '关联的源合同ID (续约或变更)'))

        # --- 手动添加的索引和约束 ---
        batch_op.create_index(batch_op.f('ix_contracts_signing_status'), ['signing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_unique_signing_token'), [ 'unique_signing_token'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_contracts_template_id_contract_templates'), 'contract_templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_contracts_previous_contract_id_contracts'), 'contracts', ['previous_contract_id'], ['id'])
        # --- 手动添加结束 ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ... (其他 batch_alter_table 块保持不变) ...

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        # --- 手动添加的删除操作 ---
        batch_op.drop_constraint(batch_op.f('fk_contracts_previous_contract_id_contracts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contracts_template_id_contract_templates'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_unique_signing_token'))
        batch_op.drop_index(batch_op.f('ix_contracts_signing_status'))
        batch_op.drop_column('previous_contract_id')
        batch_op.drop_column('unique_signing_token')
        batch_op.drop_column('employee_signature')
        batch_op.drop_column('customer_signature')
        batch_op.drop_column('signing_status')
        batch_op.drop_column('attachment_content')
        batch_op.drop_column('service_type')
        batch_op.drop_column('service_content')
        batch_op.drop_column('template_id')
        # --- 手动添加结束 ---

        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
