"""integrate_formal_contract_into_base_contract

Revision ID: 027153410068
Revises: 47cf12b8e356
Create Date: 2025-11-05 16:47:43.855050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '027153410068'
down_revision = '47cf12b8e356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ... (其他 batch_alter_table 块保持不变) ...

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        # --- 手动添加的删除操作 ---
        batch_op.drop_constraint(batch_op.f('fk_contracts_previous_contract_id_contracts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contracts_template_id_contract_templates'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_unique_signing_token'))
        batch_op.drop_index(batch_op.f('ix_contracts_signing_status'))
        batch_op.drop_column('previous_contract_id')
        batch_op.drop_column('unique_signing_token')
        batch_op.drop_column('employee_signature')
        batch_op.drop_column('customer_signature')
        batch_op.drop_column('signing_status')
        batch_op.drop_column('attachment_content')
        batch_op.drop_column('service_type')
        batch_op.drop_column('service_content')
        batch_op.drop_column('template_id')
        # --- 手动添加结束 ---

        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
