"""add pin and recent to favorites

Revision ID: 033eef3d3b59
Revises: 77fceec919ed
Create Date: 2026-05-28 10:19:49.904655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '033eef3d3b59'
down_revision = '77fceec919ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False, comment='是否置顶'))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='最近访问时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_form', schema=None) as batch_op:
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('is_pinned')
    # ### end Alembic commands ###

