"""将 PayerAlias 的唯一约束改为复合约束

Revision ID: 0345aa94a123
Revises: 75990a63dce4
Create Date: 2025-10-17 16:06:23.902693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0345aa94a123'
down_revision = '75990a63dce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payer_aliases_payer_name', type_='unique')
        batch_op.create_unique_constraint('uq_payer_name_contract_id', ['payer_name', 'contract_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payer_name_contract_id', type_='unique')
        batch_op.create_unique_constraint('uq_payer_aliases_payer_name', ['payer_name'])

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
