"""change signature columns to text type

Revision ID: 0430c6674b69
Revises: 27fdc352a12d
Create Date: 2025-11-06 16:45:52.668838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0430c6674b69'
down_revision = '27fdc352a12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('customer_signature',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               comment='客户签名',
               existing_comment='甲方签名图片URL或Base64数据',
               existing_nullable=True)
        batch_op.alter_column('employee_signature',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               comment='服务人员签名',
               existing_comment='乙方签名图片URL或Base64数据',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('employee_signature',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               comment='乙方签名图片URL或Base64数据',
               existing_comment='服务人员签名',
               existing_nullable=True)
        batch_op.alter_column('customer_signature',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               comment='甲方签名图片URL或Base64数据',
               existing_comment='客户签名',
               existing_nullable=True)

    # ### end Alembic commands ###
