"""Add wechat_openid to service_personnel

Revision ID: 05012e09dfd4
Revises: 814e056ac3aa
Create Date: 2025-12-15 10:00:04.552791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05012e09dfd4'
down_revision = '814e056ac3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wechat_openid', sa.String(length=100), nullable=True, comment='微信公众号openid'))
        batch_op.create_index(batch_op.f('ix_service_personnel_wechat_openid'), ['wechat_openid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_personnel_wechat_openid'))
        batch_op.drop_column('wechat_openid')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
