"""Remove unique constraint from jinshuju_entry_id and type on contracts

Revision ID: 07a0e4970e33
Revises: 6aac1d63e933
Create Date: 2025-11-12 22:39:07.420854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a0e4970e33'
down_revision = '6aac1d63e933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ix_contracts_jinshuju_entry_id_type', 'contracts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ix_contracts_jinshuju_entry_id_type', 'contracts', ['jinshuju_entry_id', 'type'])
    # ### end Alembic commands ###
