"""Add NannyTrialContract

Revision ID: 09d1979fa673
Revises: 7b4a45a803eb
Create Date: 2025-07-22 14:19:58.384827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d1979fa673'
down_revision = '7b4a45a803eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='合同类型鉴别器 (nanny, maternity_nurse, nanny_trial)',
               existing_comment='合同类型鉴别器 (nanny, maternity_nurse)',
               existing_nullable=False)
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active, finished, terminated, trial_active, trial_succeeded',
               existing_comment='active, finished, terminated',
               existing_nullable=False)
    op.drop_constraint('fk_exampapercourse_course_id', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey1', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_exampapercourse_course_id', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contracts', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='active, finished, terminated',
               existing_comment='active, finished, terminated, trial_active, trial_succeeded',
               existing_nullable=False)
    op.alter_column('contracts', 'type',
               existing_type=sa.VARCHAR(length=50),
               comment='合同类型鉴别器 (nanny, maternity_nurse)',
               existing_comment='合同类型鉴别器 (nanny, maternity_nurse, nanny_trial)',
               existing_nullable=False)
    # ### end Alembic commands ###
