"""modify start and end datetime

Revision ID: 0c5d641c8afc
Revises: 7723ff1d3ed4
Create Date: 2025-08-21 14:03:09.670786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5d641c8afc'
down_revision = '7723ff1d3ed4'
branch_labels = None
depends_on = None


def upgrade():
    # 【新增】在应用约束前，先填充历史数据中的空值
    from sqlalchemy.sql import table, column
    from sqlalchemy import DateTime, Date
    contracts_table = table('contracts',
        column('start_date', DateTime(timezone=True)),
        column('end_date', DateTime(timezone=True)),
        column('created_at', DateTime(timezone=True))
    )
    op.execute(
        contracts_table.update().where(contracts_table.c.start_date == None).values(start_date=contracts_table.c.created_at)
    )
    op.execute(
        contracts_table.update().where(contracts_table.c.end_date == None).values(end_date=contracts_table.c.created_at)
    )
    # 【新增结束】
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='合同开始日期与时间',
               existing_comment='合同开始日期 (育儿嫂)')
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               comment='合同结束日期与时间',
               existing_comment='合同结束日期 (育儿嫂和月嫂)')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('fk_exampapercourse_course_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_exampapercourse_course_id', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True,
               comment='合同结束日期 (育儿嫂和月嫂)',
               existing_comment='合同结束日期与时间')
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True,
               comment='合同开始日期 (育儿嫂)',
               existing_comment='合同开始日期与时间')

    # ### end Alembic commands ###
