"""Create ContractSignature table and externalize signature storage

Revision ID: 0e8b618494f4
Revises: 58406953918f
Create Date: 2025-11-15 00:54:49.680762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8b618494f4'
down_revision = '58406953918f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_signatures',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='关联的合同ID'),
    sa.Column('signature_type', sa.String(length=50), nullable=False, comment='签名类型 (customer, employee)'),
    sa.Column('file_path', sa.String(length=512), nullable=False, comment='签名文件存储路径'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型 (e.g., image/png)'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='上传时间'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'signature_type', name='uq_contract_signature_type'),
    comment='合同签名文件表'
    )
    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_signatures_contract_id'), ['contract_id'], unique=False)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('customer_signature')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_signature', sa.TEXT(), autoincrement=False, nullable=True, comment='客户签名'))

    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_signatures_contract_id'))

    op.drop_table('contract_signatures')
    # ### end Alembic commands ###
