"""Add expected_offboarding_date to BaseContract

Revision ID: 10f0251b906f
Revises: d62a64b0b234
Create Date: 2025-07-15 13:47:21.514021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f0251b906f'
down_revision = 'd62a64b0b234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('expected_offboarding_date', sa.Date(), nullable=True, comment='预计下户日期 (可动态顺延)'))
    op.alter_column('customer_bills', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否已打款')
    op.drop_index('ix_customer_bills_is_paid', table_name='customer_bills')
    op.alter_column('employee_payrolls', 'final_payout',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_comment='员工最终应领款',
               existing_nullable=False)
    op.alter_column('employee_payrolls', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否已领款')
    op.drop_index('ix_employee_payrolls_is_paid', table_name='employee_payrolls')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_employee_payrolls_is_paid', 'employee_payrolls', ['is_paid'], unique=False)
    op.alter_column('employee_payrolls', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否已领款')
    op.alter_column('employee_payrolls', 'final_payout',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_comment='员工最终应领款',
               existing_nullable=False)
    op.create_index('ix_customer_bills_is_paid', 'customer_bills', ['is_paid'], unique=False)
    op.alter_column('customer_bills', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否已打款')
    op.drop_column('contracts', 'expected_offboarding_date')
    # ### end Alembic commands ###
