"""add user_id to service_personnel table

Revision ID: 1167c21a95f7
Revises: 412afc1d2b8b
Create Date: 2025-11-10 16:47:19.974453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1167c21a95f7'
down_revision = '412afc1d2b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True, comment='关联的系统用户ID'))
        batch_op.create_index(batch_op.f('ix_service_personnel_user_id'), ['user_id'], unique=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_personnel_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
