"""replace unique_signing_token with separate customer and employee tokens

Revision ID: 127020cffe0f
Revises: 0430c6674b69
Create Date: 2025-11-06 16:49:43.919708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127020cffe0f'
down_revision = '0430c6674b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_signing_token', sa.String(length=36), nullable=True, comment='客户的专属签名令牌'))
        batch_op.add_column(sa.Column('employee_signing_token', sa.String(length=36), nullable=True, comment='服务人员的专属签名令牌'))
        batch_op.drop_index('ix_contracts_unique_signing_token')
        batch_op.create_unique_constraint(None, ['customer_signing_token'])
        batch_op.create_unique_constraint(None, ['employee_signing_token'])
        batch_op.drop_column('unique_signing_token')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_signing_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='唯一签署链接令牌'))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_contracts_unique_signing_token', ['unique_signing_token'], unique=True)
        batch_op.drop_column('employee_signing_token')
        batch_op.drop_column('customer_signing_token')

    # ### end Alembic commands ###
