"""Change signing_status to VARCHAR

Revision ID: 13b5e7655bde
Revises: c5896bcd2981
Create Date: 2025-11-06 10:24:42.401601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13b5e7655bde'
down_revision = 'c5896bcd2981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))
        batch_op.alter_column('signing_status',
               existing_type=postgresql.ENUM('unsigned', 'customer_signed', 'employee_signed', 'active', 'terminated', 'expired', name='signingstatus'),
               type_=sa.Enum('UNSIGNED', 'SIGNED', 'PENDING', 'CUSTOMER_SIGNED', 'EMPLOYEE_SIGNED', 'ACTIVE', 'TERMINATED', 'EXPIRED', name='signingstatus', native_enum=False),
               existing_comment='签署状态',
               existing_nullable=True,
               existing_server_default=sa.text("'unsigned'::signingstatus"))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('signing_status',
               existing_type=sa.Enum('UNSIGNED', 'SIGNED', 'PENDING', 'CUSTOMER_SIGNED', 'EMPLOYEE_SIGNED', 'ACTIVE', 'TERMINATED', 'EXPIRED', name='signingstatus', native_enum=False),
               type_=postgresql.ENUM('unsigned', 'customer_signed', 'employee_signed', 'active', 'terminated', 'expired', name='signingstatus'),
               existing_comment='签署状态',
               existing_nullable=True,
               existing_server_default=sa.text("'unsigned'::signingstatus"))
        batch_op.alter_column('is_auto_renew',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否自动续签',
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
