"""Add dynamic form models and update service personnel

Revision ID: 1fa24bddf243
Revises: a81cb97e539c
Create Date: 2025-11-17 23:10:58.149355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1fa24bddf243'
down_revision = 'a81cb97e539c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dynamic_form',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键，使用 UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='表单名称'),
    sa.Column('form_token', sa.String(length=100), nullable=False, comment='表单唯一标识符，用于URL或API调用'),
    sa.Column('description', sa.Text(), nullable=True, comment='表单描述'),
    sa.Column('form_type', sa.String(length=50), server_default='ACTIVE_RECORD', nullable=False, comment='表单类型 (ACTIVE_RECORD, HISTORICAL_READONLY)'),
    sa.Column('surveyjs_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='SurveyJS 兼容的表单结构 JSON'),
    sa.Column('jinshuju_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='金数据原始表单结构 JSON (用于归档和调试)'),
    sa.Column('sync_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='数据同步映射配置 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_token', name='uq_dynamic_form_token'),
    comment='动态表单定义表，存储SurveyJS表单结构和元数据'
    )
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dynamic_form_form_token'), ['form_token'], unique=True)

    op.create_table('dynamic_form_data',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键，使用 UUID'),
    sa.Column('form_id', sa.UUID(), nullable=False, comment='关联的表单定义ID'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='提交此表单的用户ID (如果适用)'),
    sa.Column('service_personnel_id', sa.UUID(), nullable=True, comment='关联的服务人员ID (如果适用，例如员工登记表)'),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='用户提交的表单数据 JSON'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_form.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_personnel_id'], ['service_personnel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='动态表单数据表，存储用户提交的表单数据'
    )
    with op.batch_alter_table('dynamic_form_data', schema=None) as batch_op:
        batch_op.create_index('idx_dynamic_form_data_form_id', ['form_id'], unique=False)
        batch_op.create_index('idx_dynamic_form_data_service_personnel_id', ['service_personnel_id'], unique=False)
        batch_op.create_index('idx_dynamic_form_data_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_contract_id', sa.UUID(), nullable=True, comment='当前关联的员工入职合同ID'))
        batch_op.create_foreign_key(None, 'contracts', ['current_contract_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_contract_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dynamic_form_data', schema=None) as batch_op:
        batch_op.drop_index('idx_dynamic_form_data_user_id')
        batch_op.drop_index('idx_dynamic_form_data_service_personnel_id')
        batch_op.drop_index('idx_dynamic_form_data_form_id')

    op.drop_table('dynamic_form_data')
    with op.batch_alter_table('dynamic_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dynamic_form_form_token'))

    op.drop_table('dynamic_form')
    # ### end Alembic commands ###
