"""Refactor AttendanceRecord model

Revision ID: 1ffb5d76f605
Revises: a67c1f268477
Create Date: 2025-07-09 14:35:03.563245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ffb5d76f605'
down_revision = 'a67c1f268477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='员工ID (可以是User或ServicePersonnel的ID)'),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_days_worked', sa.Integer(), nullable=False, comment='总出勤天数'),
    sa.Column('overtime_days', sa.Integer(), nullable=True, comment='非节假日加班天数'),
    sa.Column('statutory_holiday_days', sa.Integer(), nullable=True, comment='法定节假日工作天数'),
    sa.Column('raw_data_entry_id', sa.String(length=255), nullable=True, comment='(如果考勤来自金数据)考勤表在金数据中的Entry ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'year', 'month', name='uq_attendance_person_month'),
    comment='月度考勤记录表'
    )
    op.create_index(op.f('ix_attendance_records_contract_id'), 'attendance_records', ['contract_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_employee_id'), 'attendance_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_month'), 'attendance_records', ['month'], unique=False)
    op.create_index(op.f('ix_attendance_records_year'), 'attendance_records', ['year'], unique=False)
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_attendance_records_year'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_month'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_employee_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_contract_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
