"""remove_is_generating_bills_to_contract

Revision ID: 266b5fb63133
Revises: f970db585426
Create Date: 2025-07-29 15:43:44.744204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266b5fb63133'
down_revision = 'f970db585426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('is_generating_bills')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_generating_bills', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否正在生成账单'))

    # ### end Alembic commands ###
