"""add customer_id to contracts table

Revision ID: 27fdc352a12d
Revises: e63dc675a8a9
Create Date: 2025-11-06 16:15:59.232123

"""
from alembic import op
import sqlalchemy as sa
import uuid
from pypinyin import pinyin, Style

# revision identifiers, used by Alembic.
revision = '27fdc352a12d'
down_revision = 'e63dc675a8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Stage 1: Add the customer_id column as NULLABLE first
    op.add_column('contracts', sa.Column('customer_id', sa.UUID(), nullable=True, comment= '关联的客户ID'))

    # --- Data Migration Logic ---
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    # Define simple table representations for our query
    customer_table = sa.Table('customer', sa.MetaData(),
        sa.Column('id', sa.UUID),
        sa.Column('name', sa.String),
        sa.Column('name_pinyin', sa.String)
    )
    contract_table = sa.Table('contracts', sa.MetaData(),
        sa.Column('customer_name', sa.String)
    )

    # Find all unique customer names in the customer table
    customers_in_db = {row[0] for row in session.execute(sa.select(customer_table.c.name)).fetchall()}

    # Find all unique customer names in the contracts table
    contracts_names = {row[0] for row in session.execute(sa.select(contract_table.c.customer_name).distinct()).fetchall()}

    # Determine which names are in contracts but not in customers
    missing_names = contracts_names - customers_in_db

    if missing_names:
        print(f"Found {len(missing_names)} missing customers. Creating them now...")
        new_customers = []
        for name in missing_names:
            if not name: continue
            try:
                pinyin_full = "".join(p[0] for p in pinyin(name, style=Style.NORMAL))
                pinyin_initials = "".join(p[0] for p in pinyin(name, style=Style.FIRST_LETTER))
                pinyin_str = f"{pinyin_full} {pinyin_initials}"
            except Exception:
                pinyin_str = None

            new_customers.append({
                'id': str(uuid.uuid4()),
                'name': name,
                'name_pinyin': pinyin_str
            })

        if new_customers:
            op.bulk_insert(customer_table, new_customers)
            print(f"Successfully created {len(new_customers)} new customer records.")

    # Stage 2: Backfill the data from the customer table using customer_name
    print("Backfilling customer_id in contracts table...")
    op.execute("""
        UPDATE contracts
        SET customer_id = customer.id
        FROM customer
        WHERE contracts.customer_name = customer.name
    """)
    print("Backfill complete.")

    # Stage 3: Now that the column is populated, alter it to be NOT NULL
    print("Setting contracts.customer_id to NOT NULL...")
    op.alter_column('contracts', 'customer_id', nullable=False)

    # Create index and foreign key after the column is finalized
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_customer_id'), ['customer_id'], unique= False)
        batch_op.create_foreign_key('fk_contracts_customer_id', 'customer', ['customer_id'], [ 'id'], ondelete='RESTRICT')

    # --- Unrelated changes generated by Alembic, leave them as they are ---
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete= 'CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete= 'CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', [ 'course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', [ 'exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contracts_customer_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_customer_id'))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###