"""Link InvoiceRecord directly to CustomerBill

Revision ID: 285d938875f8
Revises: 868b81c3aaeb
Create Date: 2025-08-11 10:19:45.058082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285d938875f8'
down_revision = '868b81c3aaeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_bill_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=255), nullable=True, comment='发票号码'))
        batch_op.drop_index('ix_invoice_records_contract_id')
        batch_op.create_index(batch_op.f('ix_invoice_records_customer_bill_id'), ['customer_bill_id'], unique=False)
        batch_op.drop_constraint('invoice_records_contract_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_bills', ['customer_bill_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('status')
        batch_op.drop_column('contract_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='状态 (pending, issued)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invoice_records_contract_id_fkey', 'contracts', ['contract_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_invoice_records_customer_bill_id'))
        batch_op.create_index('ix_invoice_records_contract_id', ['contract_id'], unique=False)
        batch_op.drop_column('invoice_number')
        batch_op.drop_column('customer_bill_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
