"""Add ondelete=CASCADE to contracts.previous_contract_id

Revision ID: 29accf0d7063
Revises: 4c61a10f104f
Create Date: 2025-11-11 12:35:21.859376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29accf0d7063'
down_revision = '4c61a10f104f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('contracts_previous_contract_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'contracts', ['previous_contract_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('contracts_previous_contract_id_fkey', 'contracts', ['previous_contract_id'], ['id'])

    # ### end Alembic commands ###
