"""add management_fee_amount to contracts table

Revision ID: 30b0e8d336ca
Revises: 1ba011151e55
Create Date: 2025-08-01 10:44:22.892356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30b0e8d336ca'
down_revision = '1ba011151e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('management_fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='月管理费金额 (元/月)，从金数据同步的管理费金额',
               existing_comment='从金数据同步的管理费金额',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('management_fee_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='从金数据同步的管理费金额',
               existing_comment='月管理费金额 (元/月)，从金数据同步的管理费金额',
               existing_nullable=True)

    # ### end Alembic commands ###
