"""add_management_fee_rate_to_base_contract_and_remove_from_children

Revision ID: 33218015a4f7
Revises: 008ee2c5556f
Create Date: 2025-09-11 16:42:30.003454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33218015a4f7'
down_revision = '008ee2c5556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('management_fee_rate',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='管理费费率, e.g., 0.20 for 20%',
               existing_comment='管理费费率, e.g., 0.15 for 15%',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('fk_exampapercourse_exam_paper_id_exampaper', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('external_substitution_contract', schema=None) as batch_op:
        batch_op.drop_column('management_fee_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_substitution_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('management_fee_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False, comment='管理费率'))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_exampapercourse_exam_paper_id_exampaper', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('management_fee_rate',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='管理费费率, e.g., 0.15 for 15%',
               existing_comment='管理费费率, e.g., 0.20 for 20%',
               existing_nullable=True)

    # ### end Alembic commands ###
