"""Change date columns to datetime for contract dates

Revision ID: 3784828426b9
Revises: 66eac6778699
Create Date: 2025-08-22 11:47:35.898237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3784828426b9'
down_revision = '66eac6778699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('actual_onboarding_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_comment='实际上户日期 (月嫂)',
               existing_nullable=True)
        batch_op.alter_column('expected_offboarding_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_comment='预计下户日期 (可动态顺延)',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('expected_offboarding_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_comment='预计下户日期 (可动态顺延)',
               existing_nullable=True)
        batch_op.alter_column('actual_onboarding_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_comment='实际上户日期 (月嫂)',
               existing_nullable=True)

    # ### end Alembic commands ###
