"""Add ondelete cascade to financial activity logs

Revision ID: 39ae12372453
Revises: a52e9a06bb98
Create Date: 2025-10-29 15:12:50.012433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ae12372453'
down_revision = 'a52e9a06bb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint('financial_activity_logs_employee_payroll_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('financial_activity_logs_customer_bill_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customer_bills', ['customer_bill_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'employee_payrolls', ['employee_payroll_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_activity_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financial_activity_logs_customer_bill_id_fkey', 'customer_bills', ['customer_bill_id'], ['id'])
        batch_op.create_foreign_key('financial_activity_logs_employee_payroll_id_fkey', 'employee_payrolls', ['employee_payroll_id'], ['id'])

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
