"""Add SubstituteRecord table

Revision ID: 40547ac7c71a
Revises: 6716554472d2
Create Date: 2025-07-09 16:20:52.399115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40547ac7c71a'
down_revision = '6716554472d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('substitute_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('main_contract_id', sa.UUID(), nullable=False),
    sa.Column('substitute_user_id', sa.UUID(), nullable=True),
    sa.Column('substitute_personnel_id', sa.UUID(), nullable=True),
    sa.Column('substitute_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='替班期间的月薪标准'),
    sa.Column('substitute_management_fee', sa.Numeric(precision=10, scale=2), nullable=True, comment='替班产生的额外管理费'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True, comment='替班备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['main_contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_personnel_id'], ['service_personnel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['substitute_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='替班记录表'
    )
    op.create_index(op.f('ix_substitute_records_main_contract_id'), 'substitute_records', ['main_contract_id'], unique=False)
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_substitute_records_main_contract_id'), table_name='substitute_records')
    op.drop_table('substitute_records')
    # ### end Alembic commands ###
