"""add is_merged to customerbill

Revision ID: 405fedc90b19
Revises: 39ae12372453
Create Date: 2025-10-29 23:51:30.313141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405fedc90b19'
down_revision = '39ae12372453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_merged', sa.Boolean(), server_default='false', nullable=False, comment='是否已被合并到另一张账单'))
        batch_op.create_index(batch_op.f('ix_customer_bills_is_merged'), ['is_merged'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_bills_is_merged'))
        batch_op.drop_column('is_merged')

    # ### end Alembic commands ###
