"""add contract id in finacial adjustment

Revision ID: 4121891dfa66
Revises: d44485129755
Create Date: 2025-09-01 11:38:07.608333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4121891dfa66'
down_revision = 'd44485129755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.UUID(), nullable=True, comment='关联的合同ID (用于处理未入账的调整项)'))
        batch_op.create_index(batch_op.f('ix_financial_adjustments_contract_id'), ['contract_id'], unique=False)
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_financial_adjustments_contract_id'))
        batch_op.drop_column('contract_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
