"""Add TTS config fields to TrainingContent and TtsSentence

Revision ID: 4326b1f8c4a8
Revises: b2de2cf91f18
Create Date: 2025-06-25 10:30:36.973365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4326b1f8c4a8'
down_revision = 'b2de2cf91f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.add_column('training_content', sa.Column('default_tts_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='全局默认的TTS生成配置 (e.g., engine, prompt, temperature)'))
    op.add_column('tts_sentence', sa.Column('tts_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='针对该单句的特定TTS生成配置，覆盖全局配置'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tts_sentence', 'tts_config')
    op.drop_column('training_content', 'default_tts_config')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
