"""Update AttendanceRecord for cycle-based tracking

Revision ID: 4616b0230eb6
Revises: 40547ac7c71a
Create Date: 2025-07-10 11:09:04.426921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4616b0230eb6'
down_revision = '40547ac7c71a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_records', sa.Column('cycle_start_date', sa.Date(), nullable=False, comment='考勤周期的开始日期'))
    op.add_column('attendance_records', sa.Column('cycle_end_date', sa.Date(), nullable=False, comment='考勤周期的结束日期'))
    op.drop_index('ix_attendance_records_month', table_name='attendance_records')
    op.drop_index('ix_attendance_records_year', table_name='attendance_records')
    op.drop_constraint('uq_attendance_person_month', 'attendance_records', type_='unique')
    op.create_index(op.f('ix_attendance_records_cycle_end_date'), 'attendance_records', ['cycle_end_date'], unique=False)
    op.create_index(op.f('ix_attendance_records_cycle_start_date'), 'attendance_records', ['cycle_start_date'], unique=False)
    op.create_table_comment(
        'attendance_records',
        '考勤记录表 (可跨月)',
        existing_comment='月度考勤记录表',
        schema=None
    )
    op.drop_column('attendance_records', 'month')
    op.drop_column('attendance_records', 'year')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.add_column('attendance_records', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendance_records', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table_comment(
        'attendance_records',
        '月度考勤记录表',
        existing_comment='考勤记录表 (可跨月)',
        schema=None
    )
    op.drop_index(op.f('ix_attendance_records_cycle_start_date'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_cycle_end_date'), table_name='attendance_records')
    op.create_unique_constraint('uq_attendance_person_month', 'attendance_records', ['employee_id', 'year', 'month'])
    op.create_index('ix_attendance_records_year', 'attendance_records', ['year'], unique=False)
    op.create_index('ix_attendance_records_month', 'attendance_records', ['month'], unique=False)
    op.drop_column('attendance_records', 'cycle_end_date')
    op.drop_column('attendance_records', 'cycle_start_date')
    # ### end Alembic commands ###
