"""Add direction to BankTransaction

Revision ID: 46f07a1772ae
Revises: d83827d14652
Create Date: 2025-10-06 23:46:45.892540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f07a1772ae'
down_revision = 'd83827d14652'
branch_labels = None
depends_on = None

# --- 【新增】在这里定义 ENUM 类型 ---
transaction_direction_enum = sa.Enum('CREDIT', 'DEBIT', name='transactiondirection')
# ---------------------------------

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- 【新增】在添加列之前，先创建 ENUM 类型 ---
    transaction_direction_enum.create(op.get_bind())
    # -----------------------------------------

    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', transaction_direction_enum, nullable=False, comment='交易方向 (credit/debit)'))
        batch_op.create_index(batch_op.f('ix_bank_transactions_direction'), ['direction'], unique=False)

    # The exampapercourse changes seem unrelated, but we'll keep them as Alembic generated them.
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bank_transactions_direction'))
        batch_op.drop_column('direction')

    # --- 【新增】在最后，删除 ENUM 类型 ---
    transaction_direction_enum.drop(op.get_bind())
    # ------------------------------------

    # ### end Alembic commands ###