"""Add contract management models

Revision ID: 47cf12b8e356
Revises: 405fedc90b19
Create Date: 2025-11-05 11:54:29.684955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47cf12b8e356'
down_revision = '405fedc90b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键, UUID'),
    sa.Column('template_name', sa.String(length=255), nullable=False, comment='模板名称 (唯一)'),
    sa.Column('contract_type', sa.String(length=50), nullable=False, comment='关联的合同类型，用于鉴别'),
    sa.Column('content', sa.Text(), nullable=False, comment='合同模板内容 (Markdown 格式)'),
    sa.Column('version', sa.Integer(), nullable=False, comment='模板版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='合同模板表，存储制式合同模板'
    )
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_templates_contract_type'), ['contract_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_templates_template_name'), ['template_name'], unique=True)

    op.create_table('employee_salary_history',
    sa.Column('id', sa.UUID(), nullable=False, comment='主键, UUID'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='关联的服务人员ID'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='薪资生效日期'),
    sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=False, comment='基本薪资'),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='提成比例'),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=True, comment='奖金'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['employee_id'], ['service_personnel.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'effective_date', name='uq_employee_effective_date')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_id', sa.UUID(), nullable=True, comment='关联的合同模板ID'))
        batch_op.add_column(sa.Column('service_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='服务内容 (JSON 数组)'))
        batch_op.add_column(sa.Column('service_type', sa.String(length=50), nullable=True, comment='服务方式 (e.g., 全日住家型)'))
        batch_op.add_column(sa.Column('is_auto_renew', sa.Boolean(), server_default='false', nullable=False, comment='是否自动续签'))
        batch_op.add_column(sa.Column('attachment_content', sa.Text(), nullable=True, comment='附件内容 (Markdown 格式)'))
        batch_op.add_column(sa.Column('signing_status', sa.Enum('unsigned', 'customer_signed', 'employee_signed', 'active', 'terminated', 'expired', name='signingstatus', native_enum=False), server_default='unsigned', nullable=True, comment='签署状态'))
        batch_op.add_column(sa.Column('customer_signature', sa.String(length=512), nullable=True, comment='甲方签名图片URL或Base64数据'))
        batch_op.add_column(sa.Column('employee_signature', sa.String(length=512), nullable=True, comment='乙方签名图片URL或Base64数据'))
        batch_op.add_column(sa.Column('unique_signing_token', sa.String(length=255), nullable=True, comment='唯一签署链接令牌'))
        batch_op.add_column(sa.Column('previous_contract_id', sa.UUID(), nullable=True, comment='关联的源合同ID (续约或变更)'))
        batch_op.create_index(batch_op.f('ix_contracts_signing_status'), ['signing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_unique_signing_token'), ['unique_signing_token'], unique=True)
        batch_op.create_foreign_key(None, 'contract_templates', ['template_id'], ['id'])
        batch_op.create_foreign_key(None, 'contracts', ['previous_contract_id'], ['id'])

    # with op.batch_alter_table('customer_bills', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('is_merged', sa.Boolean(), server_default='false', nullable=False, comment='是否已被合并到另一张账单'))
    #     batch_op.create_index(batch_op.f('ix_customer_bills_is_merged'), ['is_merged'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    #     batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # with op.batch_alter_table('customer_bills', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_customer_bills_is_merged'))
    #     batch_op.drop_column('is_merged')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_contracts_unique_signing_token'))
        batch_op.drop_index(batch_op.f('ix_contracts_signing_status'))
        batch_op.drop_column('previous_contract_id')
        batch_op.drop_column('unique_signing_token')
        batch_op.drop_column('employee_signature')
        batch_op.drop_column('customer_signature')
        batch_op.drop_column('signing_status')
        batch_op.drop_column('attachment_content')
        batch_op.drop_column('is_auto_renew')
        batch_op.drop_column('service_type')
        batch_op.drop_column('service_content')
        batch_op.drop_column('template_id')

    op.drop_table('employee_salary_history')
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_templates_template_name'))
        batch_op.drop_index(batch_op.f('ix_contract_templates_contract_type'))

    op.drop_table('contract_templates')
    # ### end Alembic commands ###
