"""Refactor PayerAlias to link to contract_id

Revision ID: 4e4cda672183
Revises: 99d222e8aa1d
Create Date: 2025-10-07 00:34:48.492758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e4cda672183'
down_revision = '99d222e8aa1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.UUID(), nullable=False, comment='关联到的合同ID'))
        batch_op.drop_index('ix_payer_aliases_customer_name')
        batch_op.create_index(batch_op.f('ix_payer_aliases_contract_id'), ['contract_id'], unique=False)
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='关联到的系统内合同上的客户名称'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payer_aliases_contract_id'))
        batch_op.create_index('ix_payer_aliases_customer_name', ['customer_name'], unique=False)
        batch_op.drop_column('contract_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
