"""add_llm_management_tables

Revision ID: 5290689398cd
Revises: eae8107673d8
Create Date: 2025-05-12 10:26:49.707317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5290689398cd'
down_revision = 'eae8107673d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_name', name='uq_llm_api_key_name'),
    comment='LLM API Key 表'
    )
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_identifier', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_identifier', name='uq_llm_model_identifier'),
    sa.UniqueConstraint('model_name', name='uq_llm_model_name'),
    comment='大语言模型表'
    )
    op.create_table('llm_prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_identifier', sa.String(length=255), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('model_identifier', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['model_identifier'], ['llm_models.model_identifier'], name='fk_llm_prompt_model_identifier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_identifier', 'version', name='uq_llm_prompt_identifier_version'),
    comment='提示词模板表'
    )
    with op.batch_alter_table('llm_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_prompts_prompt_identifier'), ['prompt_identifier'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=False),
    sa.Column('llm_model_id', sa.UUID(), nullable=True),
    sa.Column('llm_prompt_id', sa.UUID(), nullable=True),
    sa.Column('api_key_name', sa.String(length=255), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parsed_output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], name='fk_llm_call_log_model_id'),
    sa.ForeignKeyConstraint(['llm_prompt_id'], ['llm_prompts.id'], name='fk_llm_call_log_prompt_id'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_llm_call_log_user_id'),
    sa.PrimaryKeyConstraint('id'),
    comment='LLM 调用日志表'
    )
    with op.batch_alter_table('evaluation_item', schema=None) as batch_op:
        batch_op.create_foreign_key('evaluation_item_category_id_fkey', 'evaluation_category', ['category_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('evaluation_item', schema=None) as batch_op:
        batch_op.drop_constraint('evaluation_item_category_id_fkey', type_='foreignkey')

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('llm_prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_prompts_prompt_identifier'))

    op.drop_table('llm_prompts')
    op.drop_table('llm_models')
    op.drop_table('llm_api_keys')
    # ### end Alembic commands ###
