"""Add FinancialActivityLog table

Revision ID: 56eab19dad5b
Revises: 0304125ae358
Create Date: 2025-07-13 15:04:33.972452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eab19dad5b'
down_revision = '0304125ae358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_bill_id', sa.UUID(), nullable=True),
    sa.Column('employee_payroll_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_bill_id'], ['customer_bills.id'], ),
    sa.ForeignKeyConstraint(['employee_payroll_id'], ['employee_payrolls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_activity_logs_customer_bill_id'), 'financial_activity_logs', ['customer_bill_id'], unique=False)
    op.create_index(op.f('ix_financial_activity_logs_employee_payroll_id'), 'financial_activity_logs', ['employee_payroll_id'], unique=False)
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_financial_activity_logs_employee_payroll_id'), table_name='financial_activity_logs')
    op.drop_index(op.f('ix_financial_activity_logs_customer_bill_id'), table_name='financial_activity_logs')
    op.drop_table('financial_activity_logs')
    # ### end Alembic commands ###
