"""Manual fix for adjustmenttype enum

Revision ID: 5709e4b34e79
Revises: cbd63e4b454a
Create Date: 2025-08-11 16:45:12.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5709e4b34e79'
down_revision = 'cbd63e4b454a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 手动添加此行来更新数据库中的 ENUM 类型
    op.execute("ALTER TYPE adjustmenttype ADD VALUE 'DEFERRED_FEE'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 从 ENUM 中移除一个值是一个复杂且可能有风险的操作，
    # 通常需要创建新类型、更新列、删除旧类型等。
    # 在此场景下，我们选择在降级时不执行任何操作。
    pass

    # ### end Alembic commands ###