"""add payer to payout_records

Revision ID: 602f3eec32f4
Revises: 769f98bd8301
Create Date: 2025-08-20 09:21:12.683602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602f3eec32f4'
down_revision = '769f98bd8301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.alter_column('payment_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='[V1遗留] 打款日期/渠道/总额/打款人等信息',
               existing_comment='打款日期/渠道/总额/打款人等信息',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('payout_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='[V1遗留] 领款人/时间/途径等信息',
               existing_comment='领款人/时间/途径等信息',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exampapercourse_course_id_3', type_='foreignkey')
        batch_op.drop_constraint('fk_exampapercourse_exam_paper_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payer', sa.String(length=50), server_default='公司代付', nullable=True, comment='付款方 (客户支付/公司代付)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_column('payer')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_exampapercourse_exam_paper_id', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_exampapercourse_course_id_3', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('payout_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='领款人/时间/途径等信息',
               existing_comment='[V1遗留] 领款人/时间/途径等信息',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.alter_column('payment_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='打款日期/渠道/总额/打款人等信息',
               existing_comment='[V1遗留] 打款日期/渠道/总额/打款人等信息',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))

    # ### end Alembic commands ###
