"""add performance indexes to contracts table

Revision ID: 609dd4616487
Revises: 6aac1d63e933
Create Date: 2025-11-13 16:01:17.392822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609dd4616487'
down_revision = '6aac1d63e933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index('ix_contracts_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_contracts_status_type', ['status', 'type'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='合同基础信息表'
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_table_comment(
        '合同基础信息表',
        existing_comment=None
    )
        batch_op.drop_constraint('uq_jinshuju_entry_type', type_='unique')
        batch_op.drop_index('ix_contracts_status_type')
        batch_op.drop_index('ix_contracts_created_at')

    # ### end Alembic commands ###
