"""add_share_slug_and_latest_flag_to_course_resource

Revision ID: 6290938714e0
Revises: 90aeb9204814
Create Date: 2025-05-22 16:32:28.581170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6290938714e0'
down_revision = '90aeb9204814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_resource', sa.Column('share_slug', sa.String(length=128), nullable=True, comment='固定分享链接的唯一标识符 (slug)'))
    op.add_column('course_resource', sa.Column('is_latest_for_slug', sa.Boolean(), server_default='false', nullable=False, comment='是否是此 share_slug 的最新版本'))
    op.create_index(op.f('ix_course_resource_share_slug'), 'course_resource', ['share_slug'], unique=True)
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_course_resource_share_slug'), table_name='course_resource')
    op.drop_column('course_resource', 'is_latest_for_slug')
    op.drop_column('course_resource', 'share_slug')
    # ### end Alembic commands ###
