"""upgrade all cycle dates to datetime

Revision ID: 66eac6778699
Revises: 0c5d641c8afc
Create Date: 2025-08-21 19:54:12.496791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eac6778699'
down_revision = '0c5d641c8afc'
branch_labels = None
depends_on = None


def upgrade():
       # 【新增】在应用约束前，先填充所有相关表中的历史空值
    from sqlalchemy.sql import table, column
    from sqlalchemy import DateTime, Date

    # 1. 更新 attendance_records 表
    attendance_table = table('attendance_records',
        column('cycle_start_date', DateTime(timezone=True)),
        column('cycle_end_date', DateTime(timezone=True)),
        column('created_at', DateTime(timezone=True))
    )
    op.execute(
        attendance_table.update().where(attendance_table.c.cycle_start_date ==None).values(cycle_start_date=attendance_table.c.created_at)
    )
    op.execute(
        attendance_table.update().where(attendance_table.c.cycle_end_date ==None).values(cycle_end_date=attendance_table.c.created_at)
    )

    # 2. 更新 customer_bills 表
    bills_table = table('customer_bills',
        column('cycle_start_date', DateTime(timezone=True)),
        column('cycle_end_date', DateTime(timezone=True)),
        column('created_at', DateTime(timezone=True))
    )
    op.execute(
        bills_table.update().where(bills_table.c.cycle_start_date == None).values(cycle_start_date=bills_table.c.created_at)
    )
    op.execute(
        bills_table.update().where(bills_table.c.cycle_end_date == None).values(cycle_end_date=bills_table.c.created_at)
    )

    # 3. 更新 employee_payrolls 表
    payrolls_table = table('employee_payrolls',
        column('cycle_start_date', DateTime(timezone=True)),
        column('cycle_end_date', DateTime(timezone=True)),
        column('created_at', DateTime(timezone=True))
    )
    op.execute(
        payrolls_table.update().where(payrolls_table.c.cycle_start_date == None).values(cycle_start_date=payrolls_table.c.created_at)
    )
    op.execute(
        payrolls_table.update().where(payrolls_table.c.cycle_end_date == None).values(cycle_end_date=payrolls_table.c.created_at)
    )
    # 【新增结束】
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               comment=None,
               existing_comment='考勤周期的开始日期',
               existing_nullable=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               comment=None,
               existing_comment='考勤周期的结束日期',
               existing_nullable=False)
        batch_op.drop_index('ix_attendance_records_cycle_end_date')
        batch_op.drop_index('ix_attendance_records_cycle_start_date')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_index('ix_customer_bills_cycle_start_date')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
        batch_op.drop_index('ix_employee_payrolls_cycle_start_date')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('fk_exampapercourse_exam_paper_id_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_exampapercourse_exam_paper_id_3', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.create_index('ix_employee_payrolls_cycle_start_date', ['cycle_start_date'], unique=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.create_index('ix_customer_bills_cycle_start_date', ['cycle_start_date'], unique=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index('ix_attendance_records_cycle_start_date', ['cycle_start_date'], unique=False)
        batch_op.create_index('ix_attendance_records_cycle_end_date', ['cycle_end_date'], unique=False)
        batch_op.alter_column('cycle_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               comment='考勤周期的结束日期',
               existing_nullable=False)
        batch_op.alter_column('cycle_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               comment='考勤周期的开始日期',
               existing_nullable=False)

    # ### end Alembic commands ###
