"""Remove foreign key constraint from employee_payrolls.employee_id

Revision ID: 6716554472d2
Revises: 1ffb5d76f605
Create Date: 2025-07-09 14:53:17.499728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6716554472d2'
down_revision = '1ffb5d76f605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_payrolls', 'employee_id',
               existing_type=sa.UUID(),
               comment='员工ID (可以是User或ServicePersonnel的ID)',
               existing_nullable=False)
    op.drop_constraint('employee_payrolls_employee_id_fkey', 'employee_payrolls', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('employee_payrolls_employee_id_fkey', 'employee_payrolls', 'service_personnel', ['employee_id'], ['id'])
    op.alter_column('employee_payrolls', 'employee_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='员工ID (可以是User或ServicePersonnel的ID)',
               existing_nullable=False)
    # ### end Alembic commands ###
