"""Remove default value from deposit_amount in contracts table

Revision ID: 6aac1d63e933
Revises: a2e793a75a81
Create Date: 2025-11-11 13:23:51.517886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aac1d63e933'
down_revision = 'a2e793a75a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('3000'))
    # ### end Alembic commands ###
