'''Add company_paid_salary to AdjustmentType enum

Revision ID: 6de67bef62ab
Revises: 33218015a4f7
Create Date: 2025-09-23 15:28:03.633594

'''
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de67bef62ab'
down_revision = '33218015a4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE adjustmenttype ADD VALUE 'COMPANY_PAID_SALARY'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Downgrading enum is complex and potentially data-lossy, skipping for now.
    pass
    # ### end Alembic commands ###