"""Add CompanyBankAccount table

Revision ID: 6fe1dea21602
Revises: 06cc940a7c66
Create Date: 2025-09-25 13:49:03.883910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe1dea21602'
down_revision = '06cc940a7c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_nickname', sa.String(length=100), nullable=False, comment="账户别名，如 '公司招行主账户'"),
    sa.Column('payee_name', sa.String(length=100), nullable=False, comment='收款户名'),
    sa.Column('account_number', sa.String(length=100), nullable=False, comment='银行账号'),
    sa.Column('bank_name', sa.String(length=200), nullable=False, comment='开户行全称'),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False, comment='是否为默认账户'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id'),
    comment='公司收款账户信息'
    )
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    op.drop_table('company_bank_accounts')
    # ### end Alembic commands ###
