"""Add payee_alias table

Revision ID: 75990a63dce4
Revises: 9de0e3d0c5b8
Create Date: 2025-10-16 14:56:11.453795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75990a63dce4'
down_revision = '9de0e3d0c5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payee_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False, comment='银行流水中的收款方名称（代收人）'),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_service_personnel_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_service_personnel_id'], ['service_personnel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name', name='uq_payee_aliases_alias_name'),
    comment='收款人别名表（用于代收工资等场景）'
    )
    with op.batch_alter_table('payee_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payee_aliases_alias_name'), ['alias_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_payee_aliases_target_service_personnel_id'), ['target_service_personnel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payee_aliases_target_user_id'), ['target_user_id'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payee_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payee_aliases_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_payee_aliases_target_service_personnel_id'))
        batch_op.drop_index(batch_op.f('ix_payee_aliases_alias_name'))

    op.drop_table('payee_aliases')
    # ### end Alembic commands ###
