"""add settlement status to financial adjustments

Revision ID: 7789538d82d4
Revises: a62e1d689709
Create Date: 2025-08-18 11:24:00.111028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7789538d82d4'
down_revision = 'a62e1d689709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_settled', sa.Boolean(), server_default='false', nullable=False, comment='是否已结算 (收/付款完成)'))
        batch_op.add_column(sa.Column('settlement_date', sa.Date(), nullable=True, comment='结算日期 (收/付款日期)'))
        batch_op.add_column(sa.Column('settlement_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="结算详情 (e.g., {'method': '支付宝', 'notes': 'xxx', 'image_url': '...' })"))
        batch_op.create_index(batch_op.f('ix_financial_adjustments_is_settled'), ['is_settled'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_adjustments_is_settled'))
        batch_op.drop_column('settlement_details')
        batch_op.drop_column('settlement_date')
        batch_op.drop_column('is_settled')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
