"""Add management_fee_status to nanny_contract

Revision ID: 77d5e350c786
Revises: a5caeddd0648
Create Date: 2025-07-17 11:04:37.812619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77d5e350c786'
down_revision = 'a5caeddd0648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('management_fee_status', sa.String(length=50), nullable=True, comment='(年签)管理费支付状态 (pending, paid, partial)'))
        batch_op.alter_column('is_monthly_auto_renew',
               existing_type=sa.BOOLEAN(),
               comment='是否为自动续约的月签合同',
               existing_nullable=True)
        batch_op.alter_column('management_fee_paid_months',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='(月签)已缴管理费的月份列表 (e.g., ["2024-06"])',
               existing_comment='已缴管理费的月份列表 (e.g., ["2024-06"])',
               existing_nullable=True)
        batch_op.alter_column('is_first_month_fee_paid',
               existing_type=sa.BOOLEAN(),
               comment='(年签)是否已缴首期全额管理费',
               existing_comment='是否已缴首月10%上户费',
               existing_nullable=True)

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               comment='创建时间',
               existing_comment='考试时间 (开始时间)',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exampapercourse_exam_paper_id', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_exampapercourse_exam_paper_id', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True, precision=6),
               comment='考试时间 (开始时间)',
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('is_first_month_fee_paid',
               existing_type=sa.BOOLEAN(),
               comment='是否已缴首月10%上户费',
               existing_comment='(年签)是否已缴首期全额管理费',
               existing_nullable=True)
        batch_op.alter_column('management_fee_paid_months',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='已缴管理费的月份列表 (e.g., ["2024-06"])',
               existing_comment='(月签)已缴管理费的月份列表 (e.g., ["2024-06"])',
               existing_nullable=True)
        batch_op.alter_column('is_monthly_auto_renew',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='是否为自动续约的月签合同',
               existing_nullable=True)
        batch_op.drop_column('management_fee_status')

    # ### end Alembic commands ###
