"""add user favorite forms

Revision ID: 77fceec919ed
Revises: 35b0453c5291
Create Date: 2026-05-28 10:12:41.300743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77fceec919ed'
down_revision = '35b0453c5291'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['dynamic_form.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'form_id', name='uq_user_form_favorite'),
    comment='用户常用表单关联表'
    )
    with op.batch_alter_table('user_favorite_form', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_favorite_form_form_id'), ['form_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_favorite_form_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorite_form', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_favorite_form_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_favorite_form_form_id'))

    op.drop_table('user_favorite_form')
    # ### end Alembic commands ###

