"""Add actual_work_days to bills and payrolls

Revision ID: 7a59617af781
Revises: d1987a12a9b3
Create Date: 2025-08-01 16:09:20.970752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a59617af781'
down_revision = 'd1987a12a9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_work_days', sa.Integer(), nullable=True, comment='实际劳务天数'))

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_work_days', sa.Integer(), nullable=True, comment='实际劳务天数'))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.drop_column('actual_work_days')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_column('actual_work_days')

    # ### end Alembic commands ###
