"""Add unique constraints to bills and payrollss

Revision ID: 7b4a45a803eb
Revises: 77d5e350c786
Create Date: 2025-07-21 18:36:19.109182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4a45a803eb'
down_revision = '77d5e350c786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bill_contract_period', 'customer_bills', ['contract_id', 'year', 'month', 'cycle_start_date'])
    op.create_unique_constraint('uq_payroll_contract_period', 'employee_payrolls', ['contract_id', 'year', 'month', 'cycle_start_date'])
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_payroll_contract_period', 'employee_payrolls', type_='unique')
    op.drop_constraint('uq_bill_contract_period', 'customer_bills', type_='unique')
    # ### end Alembic commands ###
