"""fix_substitute_relations_v2

Revision ID: 7f6388bb6fb1
Revises: 3e10a5bcf691
Create Date: 2025-07-23 15:34:24.047476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6388bb6fb1'
down_revision = '3e10a5bcf691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_bills_source_substitute_record_id', table_name='customer_bills')
    op.drop_constraint('customer_bills_source_substitute_record_id_fkey', 'customer_bills', type_='foreignkey')
    op.drop_column('customer_bills', 'source_substitute_record_id')
    op.drop_index('ix_employee_payrolls_source_substitute_record_id', table_name='employee_payrolls')
    op.drop_constraint('employee_payrolls_source_substitute_record_id_fkey', 'employee_payrolls', type_='foreignkey')
    op.drop_column('employee_payrolls', 'source_substitute_record_id')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey1', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey1', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey1', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.add_column('employee_payrolls', sa.Column('source_substitute_record_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的替班记录ID'))
    op.create_foreign_key('employee_payrolls_source_substitute_record_id_fkey', 'employee_payrolls', 'substitute_records', ['source_substitute_record_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_employee_payrolls_source_substitute_record_id', 'employee_payrolls', ['source_substitute_record_id'], unique=False)
    op.add_column('customer_bills', sa.Column('source_substitute_record_id', sa.UUID(), autoincrement=False, nullable=True, comment='关联的替班记录ID'))
    op.create_foreign_key('customer_bills_source_substitute_record_id_fkey', 'customer_bills', 'substitute_records', ['source_substitute_record_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_customer_bills_source_substitute_record_id', 'customer_bills', ['source_substitute_record_id'], unique=False)
    # ### end Alembic commands ###
