"""add_wechat_message_logs_table

Revision ID: 83b7d0a869a9
Revises: 033eef3d3b59
Create Date: 2026-05-28 12:02:59.618464

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '83b7d0a869a9'
down_revision = '033eef3d3b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_message_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='消息类型 (SIGN_CUSTOMER, SIGN_EMPLOYEE, SIGN_FULLY, TRIAL_EXPIRING, CONTRACT_EXPIRING, PREGNANCY_ALERT, ATTENDANCE_REMINDER)'),
    sa.Column('touser', sa.String(length=255), nullable=False, comment='接收者'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='卡片标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='卡片正文'),
    sa.Column('jump_url', sa.String(length=512), nullable=True, comment='跳转URL'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='发送状态 (SUCCESS, FAILED)'),
    sa.Column('error_details', sa.Text(), nullable=True, comment='微信API返回的错误详情'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='发送时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='企业微信通知发送日志审计表'
    )
    with op.batch_alter_table('wechat_message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wechat_message_logs_message_type'), ['message_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_message_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_wechat_message_logs_touser'), ['touser'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wechat_message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wechat_message_logs_touser'))
        batch_op.drop_index(batch_op.f('ix_wechat_message_logs_status'))
        batch_op.drop_index(batch_op.f('ix_wechat_message_logs_message_type'))

    op.drop_table('wechat_message_logs')
    # ### end Alembic commands ###
