"""Add management_fee_rate and ensure management_fee_amount exists

Revision ID: 88fe75840193
Revises: 8b06737ac086
Create Date: 2025-07-09 13:48:58.897295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fe75840193'
down_revision = '8b06737ac086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.UUID(), nullable=True, comment='关联到系统用户 (如果是内部员工)'))
    op.add_column('contracts', sa.Column('service_personnel_id', sa.UUID(), nullable=True, comment='关联到外部服务人员'))
    op.drop_index('ix_contracts_employee_id', table_name='contracts')
    op.create_index(op.f('ix_contracts_service_personnel_id'), 'contracts', ['service_personnel_id'], unique=False)
    op.create_index(op.f('ix_contracts_user_id'), 'contracts', ['user_id'], unique=False)
    op.drop_constraint('contracts_employee_id_fkey', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'service_personnel', ['service_personnel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'contracts', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('contracts', 'employee_id')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.add_column('contracts', sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_employee_id_fkey', 'contracts', 'service_personnel', ['employee_id'], ['id'])
    op.drop_index(op.f('ix_contracts_user_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_service_personnel_id'), table_name='contracts')
    op.create_index('ix_contracts_employee_id', 'contracts', ['employee_id'], unique=False)
    op.drop_column('contracts', 'service_personnel_id')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
