"""Add management_fee_rate and ensure management_fee_amount exists

Revision ID: 8b06737ac086
Revises: c1a76f7b6856
Create Date: 2025-07-09 13:26:03.136719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b06737ac086'
down_revision = 'c1a76f7b6856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('management_fee_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='从金数据同步的管理费金额'))
    op.alter_column('contracts', 'management_fee_rate',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='管理费费率, e.g., 0.15 for 15%',
               existing_comment='管理费率, 0.15或0.25',
               existing_nullable=True)
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('contracts', 'management_fee_rate',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='管理费率, 0.15或0.25',
               existing_comment='管理费费率, e.g., 0.15 for 15%',
               existing_nullable=True)
    op.drop_column('contracts', 'management_fee_amount')
    # ### end Alembic commands ###
