"""Add unique constraints to bills and payrolls

Revision ID: 8c0e473c8bae
Revises: 8cb818e0ef22
Create Date: 2025-07-27 10:43:29.829365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0e473c8bae'
down_revision = '8cb818e0ef22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bill_contract_period', type_='unique')
        batch_op.create_unique_constraint('uq_bill_contract_cycle_is_sub', ['contract_id', 'cycle_start_date', 'is_substitute_bill'])

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payroll_contract_period', type_='unique')
        batch_op.create_unique_constraint('uq_payroll_contract_cycle_is_sub', ['contract_id', 'cycle_start_date', 'is_substitute_payroll'])

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.drop_column('management_fee_rate')
        batch_op.drop_column('substitute_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitute_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='替班天数'))
        batch_op.add_column(sa.Column('management_fee_rate', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True, comment='替班期间的管理费费率 (仅月嫂)'))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payroll_contract_cycle_is_sub', type_='unique')
        batch_op.create_unique_constraint('uq_payroll_contract_period', ['contract_id', 'year', 'month', 'cycle_start_date', 'source_substitute_record_id'])

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bill_contract_cycle_is_sub', type_='unique')
        batch_op.create_unique_constraint('uq_bill_contract_period', ['contract_id', 'year', 'month', 'cycle_start_date', 'source_substitute_record_id'])

    # ### end Alembic commands ###
