"""Add substitute_type to SubstituteRecord

Revision ID: 8cb818e0ef22
Revises: 0209f3f4285c
Create Date: 2025-07-25 16:06:04.640354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb818e0ef22'
down_revision = '0209f3f4285c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitute_type', sa.String(length=50), nullable=False, server_default='unknown', comment='替班人员类型 (maternity_nurse, nanny)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.drop_column('substitute_type')

    # ### end Alembic commands ###
