"""add_substitute_billing_relations

Revision ID: 8d06e68a80ea
Revises: 09d1979fa673
Create Date: 2025-07-23 15:00:25.751038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d06e68a80ea'
down_revision = '09d1979fa673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_substitute_bill', sa.Boolean(), server_default='false', nullable=False, comment='是否为替班账单'))
        batch_op.add_column(sa.Column('source_substitute_record_id', sa.UUID(), nullable=True, comment='关联的替班记录ID'))
        batch_op.create_index(batch_op.f('ix_customer_bills_is_substitute_bill'), ['is_substitute_bill'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_bills_source_substitute_record_id'), ['source_substitute_record_id'], unique=False)
        batch_op.create_foreign_key(None, 'substitute_records', ['source_substitute_record_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_substitute_payroll', sa.Boolean(), server_default='false', nullable=False, comment='是否为替班薪酬单'))
        batch_op.add_column(sa.Column('source_substitute_record_id', sa.UUID(), nullable=True, comment='关联的替班记录ID'))
        batch_op.create_index(batch_op.f('ix_employee_payrolls_is_substitute_payroll'), ['is_substitute_payroll'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_payrolls_source_substitute_record_id'), ['source_substitute_record_id'], unique=False)
        batch_op.create_foreign_key(None, 'substitute_records', ['source_substitute_record_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_bill_id', sa.UUID(), nullable=True, comment='生成的替班账单ID'))
        batch_op.add_column(sa.Column('generated_payroll_id', sa.UUID(), nullable=True, comment='生成的替班薪酬单ID'))
        batch_op.create_foreign_key(None, 'employee_payrolls', ['generated_payroll_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'customer_bills', ['generated_bill_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('generated_payroll_id')
        batch_op.drop_column('generated_bill_id')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_employee_payrolls_source_substitute_record_id'))
        batch_op.drop_index(batch_op.f('ix_employee_payrolls_is_substitute_payroll'))
        batch_op.drop_column('source_substitute_record_id')
        batch_op.drop_column('is_substitute_payroll')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_bills_source_substitute_record_id'))
        batch_op.drop_index(batch_op.f('ix_customer_bills_is_substitute_bill'))
        batch_op.drop_column('source_substitute_record_id')
        batch_op.drop_column('is_substitute_bill')

    # ### end Alembic commands ###
