"""add user course and resource access permission tables

Revision ID: 90aeb9204814
Revises: 01a2c6fb43e7
Create Date: 2025-05-20 14:23:46.434954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90aeb9204814'
down_revision = '01a2c6fb43e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_course_access',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('course_id', sa.UUID(), nullable=False, comment='课程ID'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.ForeignKeyConstraint(['course_id'], ['trainingcourse.id'], name='fk_usercourseaccess_course_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_usercourseaccess_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='pk_user_course_access'),
    comment='用户课程访问权限表 (哪些用户可以访问哪些课程)'
    )
    op.create_table('user_resource_access',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='用户ID'),
    sa.Column('resource_id', sa.UUID(), nullable=False, comment='课程资源ID'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='授权时间'),
    sa.ForeignKeyConstraint(['resource_id'], ['course_resource.id'], name='fk_userresourceaccess_resource_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_userresourceaccess_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'resource_id', name='pk_user_resource_access'),
    comment='用户课程资源访问权限表 (哪些用户可以访问特定课程下的哪些资源)'
    )
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_resource_access')
    op.drop_table('user_course_access')
    # ### end Alembic commands ###
