"""add_overtime_days_to_substitute_records

Revision ID: 92aa574c3ac2
Revises: 0c99d367415f
Create Date: 2025-07-24 12:30:49.479325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92aa574c3ac2'
down_revision = '0c99d367415f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overtime_days', sa.Integer(), nullable=False, server_default='0', comment='替班期间的加班天数'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.drop_column('overtime_days')

    # ### end Alembic commands ###