"""Refactor PayerAlias model

Revision ID: 99d222e8aa1d
Revises: 46f07a1772ae
Create Date: 2025-10-07 00:11:13.896683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d222e8aa1d'
down_revision = '46f07a1772ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=False, comment='关联到的系统内合同上的客户名称'))
        batch_op.drop_index('ix_payer_aliases_customer_id')
        batch_op.drop_constraint('uq_payer_name_customer_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_payer_aliases_customer_name'), ['customer_name'], unique=False)
        batch_op.create_unique_constraint('uq_payer_aliases_payer_name', ['payer_name'])
        batch_op.drop_constraint('payer_aliases_customer_id_fkey', type_='foreignkey')
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payer_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=False, comment='关联的系统客户ID'))
        batch_op.create_foreign_key('payer_aliases_customer_id_fkey', 'customer', ['customer_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_payer_aliases_payer_name', type_='unique')
        batch_op.drop_index(batch_op.f('ix_payer_aliases_customer_name'))
        batch_op.create_unique_constraint('uq_payer_name_customer_id', ['payer_name', 'customer_id'])
        batch_op.create_index('ix_payer_aliases_customer_id', ['customer_id'], unique=False)
        batch_op.drop_column('customer_name')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
