"""add_merged_audio_segment_table

Revision ID: 9c1e9bb0434c
Revises: de37ab4634d6
Create Date: 2025-05-19 12:06:51.118414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1e9bb0434c'
down_revision = 'de37ab4634d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merged_audio_segment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merged_audio_id', sa.UUID(), nullable=False),
    sa.Column('tts_sentence_id', sa.UUID(), nullable=True),
    sa.Column('original_order_index', sa.Integer(), nullable=False, comment='The order_index of the sentence in its original TtsScript at the time of merging'),
    sa.Column('original_sentence_text_ref', sa.Text(), nullable=True, comment='Sentence text at the time of merging'),
    sa.Column('start_ms', sa.Integer(), nullable=False, comment='Start time of this segment in the merged audio (milliseconds)'),
    sa.Column('end_ms', sa.Integer(), nullable=False, comment='End time of this segment in the merged audio (milliseconds)'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Duration of this segment in milliseconds (calculated as end_ms - start_ms)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merged_audio_id'], ['tts_audio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tts_sentence_id'], ['tts_sentence.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Segments of a merged TTS audio, mapping to original sentences and their timings.'
    )
    op.create_index('idx_merged_audio_segment_audio_order', 'merged_audio_segment', ['merged_audio_id', 'original_order_index'], unique=False)
    op.create_index(op.f('ix_merged_audio_segment_merged_audio_id'), 'merged_audio_segment', ['merged_audio_id'], unique=False)
    op.create_index(op.f('ix_merged_audio_segment_tts_sentence_id'), 'merged_audio_segment', ['tts_sentence_id'], unique=False)
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_merged_audio_segment_tts_sentence_id'), table_name='merged_audio_segment')
    op.drop_index(op.f('ix_merged_audio_segment_merged_audio_id'), table_name='merged_audio_segment')
    op.drop_index('idx_merged_audio_segment_audio_order', table_name='merged_audio_segment')
    op.drop_table('merged_audio_segment')
    # ### end Alembic commands ###
