"""Add permanent_ignore_list table

Revision ID: 9de0e3d0c5b8
Revises: def6e5037fe6
Create Date: 2025-10-16 13:12:51.716815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9de0e3d0c5b8'
down_revision = 'def6e5037fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanent_ignore_list',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False, comment='要忽略的收/付款方名称'),
    sa.Column('direction', sa.Enum('CREDIT', 'DEBIT', name='transactiondirection_permanent_ignore'), nullable=False, comment='交易方向 (CREDIT/DEBIT)'),
    sa.Column('initial_remark', sa.Text(), nullable=True, comment='首次忽略时填写的原始原因'),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payer_name', 'direction', name='uq_payer_name_direction'),
    comment='永久忽略名单'
    )
    with op.batch_alter_table('permanent_ignore_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permanent_ignore_list_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_permanent_ignore_list_payer_name'), ['payer_name'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('permanent_ignore_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permanent_ignore_list_payer_name'))
        batch_op.drop_index(batch_op.f('ix_permanent_ignore_list_direction'))

    op.drop_table('permanent_ignore_list')
    # ### end Alembic commands ###
