"""Create composite unique index on contracts for entry_id and type

Revision ID: a5caeddd0648
Revises: 9c1e9bb0434c
Create Date: 2025-07-17 10:18:11.329722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a5caeddd0648'
down_revision = 'e083cc28df75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_jinshuju_entry_id')
        batch_op.create_index('ix_contracts_jinshuju_entry_id_type', ['jinshuju_entry_id', 'type'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index('ix_contracts_jinshuju_entry_id_type')
        batch_op.create_index('ix_contracts_jinshuju_entry_id', ['jinshuju_entry_id'], unique=True)

    # ### end Alembic commands ###