"""Make jinshuju_entry_id on contract nullable

Revision ID: a62e1d689709
Revises: 0d32a26b7358
Create Date: 2025-08-14 12:09:36.508174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62e1d689709'
down_revision = '0d32a26b7358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('jinshuju_entry_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='金数据中的原始数据Entry ID或serial_number')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('jinshuju_entry_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='金数据中的原始数据Entry ID或serial_number')

    # ### end Alembic commands ###
