"""Support precise time and decimal days

Revision ID: ac8dff6f3f84
Revises: d63bbdbe438f
Create Date: 2025-08-04 17:02:36.497275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8dff6f3f84'
down_revision = 'd63bbdbe438f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('total_days_worked',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment='总出勤天数',
               existing_comment='总出勤天数 (例如 26 + 加班)')
        batch_op.alter_column('overtime_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='非节假日加班天数',
               existing_comment='加班天数')
        batch_op.alter_column('statutory_holiday_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='法定节假日工作天数',
               existing_comment='法定节假日加班天数')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实际劳务天数',
               existing_comment='实际劳务天数 (由运营手动调整，用于育儿嫂合同)',
               existing_nullable=True)

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实际劳务天数',
               existing_comment='实际劳务天数 (由运营手动调整，用于育儿嫂合同)',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               comment='替班开始日期时间',
               existing_nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               comment='替班结束日期时间',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               comment=None,
               existing_comment='替班结束日期时间',
               existing_nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               comment=None,
               existing_comment='替班开始日期时间',
               existing_nullable=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实际劳务天数 (由运营手动调整，用于育儿嫂合同)',
               existing_comment='实际劳务天数',
               existing_nullable=True)

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='实际劳务天数 (由运营手动调整，用于育儿嫂合同)',
               existing_comment='实际劳务天数',
               existing_nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('statutory_holiday_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment='法定节假日加班天数',
               existing_comment='法定节假日工作天数')
        batch_op.alter_column('overtime_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               comment='加班天数',
               existing_comment='非节假日加班天数')
        batch_op.alter_column('total_days_worked',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               comment='总出勤天数 (例如 26 + 加班)',
               existing_comment='总出勤天数')

    # ### end Alembic commands ###
