"""add_expires_at_to_user_resource_access

Revision ID: bcef44d35683
Revises: 7228dc2a7677
Create Date: 2025-05-23 10:10:34.009190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcef44d35683'
down_revision = '7228dc2a7677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.add_column('user_resource_access', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='权限过期时间 (NULL表示永久)'))
    op.create_table_comment(
        'user_resource_access',
        '用户课程资源访问权限表',
        existing_comment='用户课程资源访问权限表 (哪些用户可以访问特定课程下的哪些资源)',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_resource_access',
        '用户课程资源访问权限表 (哪些用户可以访问特定课程下的哪些资源)',
        existing_comment='用户课程资源访问权限表',
        schema=None
    )
    op.drop_column('user_resource_access', 'expires_at')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
