"""Add jinshuju_entry_id to BaseContract

Revision ID: c1a76f7b6856
Revises: 23ecaf0a5143
Create Date: 2025-07-09 13:12:47.466847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1a76f7b6856'
down_revision = '23ecaf0a5143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('jinshuju_entry_id', sa.String(length=255), nullable=False, comment='金数据中的原始数据Entry ID或serial_number'))
    op.create_index(op.f('ix_contracts_jinshuju_entry_id'), 'contracts', ['jinshuju_entry_id'], unique=True)
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contracts_jinshuju_entry_id'), table_name='contracts')
    op.drop_column('contracts', 'jinshuju_entry_id')
    # ### end Alembic commands ###
