"""verify_sync

Revision ID: c5896bcd2981
Revises: 027153410068
Create Date: 2025-11-05 16:59:43.898081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5896bcd2981'
down_revision = '027153410068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    # --- 针对 customer 表的修改 ---
    # 1. 先添加 name 列，允许为 NULL
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True, comment= '客户姓名'))

    # 2. 填充 name 列的数据
    # 注意：这里 op.execute() 必须在 batch_alter_table 块之外，确保 name 列已存在
    op.execute("UPDATE customer SET name = COALESCE(first_name, '') || COALESCE(' ' || last_name, '')")

    # 3. 修改 name 列为 NOT NULL，并添加其他列、索引和约束，删除旧列
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               nullable=False,
               existing_comment='客户姓名')
        batch_op.add_column(sa.Column('name_pinyin', sa.String(length=500), nullable=True, comment='客户姓名拼音'))
        batch_op.add_column(sa.Column('id_card_number', sa.String(length=100), nullable=True, comment='身份证号, 可选但唯一'))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True, comment='客户地址'))
        batch_op.create_index(batch_op.f('ix_customer_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_name_pinyin'), ['name_pinyin'], unique= False)
        batch_op.create_unique_constraint(batch_op.f('uq_customer_id_card_number'), [ 'id_card_number'])
        batch_op.drop_column('title')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.UUID(), nullable=False, comment='导致此次薪资变更的合同ID'))
        batch_op.create_foreign_key(None, 'contracts', ['contract_id'], ['id'])

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True, comment='员工住址'))
        batch_op.alter_column('id_card_number',
               existing_type=sa.VARCHAR(length=100),
               comment='身份证号, 可选但唯一',
               existing_comment='身份证号, 可选',
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['id_card_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_personnel', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id_card_number',
               existing_type=sa.VARCHAR(length=100),
               comment='身份证号, 可选',
               existing_comment='身份证号, 可选但唯一',
               existing_nullable=True)
        batch_op.drop_column('address')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_salary_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contract_id')

    # 1. 重新添加旧列
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='客户的姓'))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='客户的名'))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='称谓 (先生/女士/小姐等)'))

        # 2. 删除新列的索引和约束
        batch_op.drop_constraint(batch_op.f('uq_customer_id_card_number'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_customer_name_pinyin'))
        batch_op.drop_index(batch_op.f('ix_customer_name'))

        # 3. 删除新列
        batch_op.drop_column('address')
        batch_op.drop_column('id_card_number')
        batch_op.drop_column('name_pinyin')
        batch_op.drop_column('name') # 最后删除 name 列

    # 4. 恢复 name 列为 NOT NULL (如果之前是 NOT NULL)
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               nullable=False, # 假设 first_name 之前是 NOT NULL
               existing_comment='客户姓名')


    # ### end Alembic commands ###
