"""Add deferred status and type for customer bills

Revision ID: cbd63e4b454a
Revises: 5007aa6c9b2e
Create Date: 2025-08-11 16:12:04.824418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbd63e4b454a'
down_revision = '5007aa6c9b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deferred', sa.Boolean(), server_default='false', nullable=False, comment='是否已顺延'))
        batch_op.create_index(batch_op.f('ix_customer_bills_is_deferred'), ['is_deferred'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_bills_is_deferred'))
        batch_op.drop_column('is_deferred')

    # ### end Alembic commands ###
