"""Add MonthlyStatement model and link to CustomerBill

Revision ID: cf6c5d93c325
Revises: 484ea6ba4f2e
Create Date: 2025-09-26 15:39:53.895551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6c5d93c325'
down_revision = '484ea6ba4f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='UNPAID', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_name', 'year', 'month', name='uq_customer_name_year_month'),
    comment='月度结算单，用于聚合客户的月度账单'
    )
    with op.batch_alter_table('monthly_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_statements_customer_name'), ['customer_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_statements_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_statements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_statements_year'), ['year'], unique=False)

    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statement_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_bills_statement_id'), ['statement_id'], unique=False)
        batch_op.create_foreign_key(None, 'monthly_statements', ['statement_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bills', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_customer_bills_statement_id'))
        batch_op.drop_column('statement_id')

    with op.batch_alter_table('monthly_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_statements_year'))
        batch_op.drop_index(batch_op.f('ix_monthly_statements_status'))
        batch_op.drop_index(batch_op.f('ix_monthly_statements_month'))
        batch_op.drop_index(batch_op.f('ix_monthly_statements_customer_name'))

    op.drop_table('monthly_statements')
    # ### end Alembic commands ###
