"""add status and payment info to financial adjustments

Revision ID: d44485129755
Revises: 91c85446dc72
Create Date: 2025-09-01 11:04:04.626656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44485129755'
down_revision = '91c85446dc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), server_default='PENDING', nullable=False, comment='调整项生命周期状态 (PENDING, PAID, BILLED)'))
        batch_op.add_column(sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='账单前支付金额 (用于定金)'))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='账单前支付时间(用于定金)'))
        batch_op.create_index(batch_op.f('ix_financial_adjustments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_adjustments_status'))
        batch_op.drop_column('paid_at')
        batch_op.drop_column('paid_amount')
        batch_op.drop_column('status')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
