"""Switch bills and payrolls to cycle-based model

Revision ID: d6e7d1fe9717
Revises: 10f0251b906f
Create Date: 2025-07-15 15:45:15.085752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e7d1fe9717'
down_revision = '10f0251b906f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_bills', sa.Column('cycle_start_date', sa.Date(), nullable=False))
    op.add_column('customer_bills', sa.Column('cycle_end_date', sa.Date(), nullable=False))
    op.drop_constraint('uq_bill_contract_month', 'customer_bills', type_='unique')
    op.create_index(op.f('ix_customer_bills_cycle_end_date'), 'customer_bills', ['cycle_end_date'], unique=False)
    op.create_index(op.f('ix_customer_bills_cycle_start_date'), 'customer_bills', ['cycle_start_date'], unique=False)
    op.create_unique_constraint('uq_bill_contract_cycle_start', 'customer_bills', ['contract_id', 'cycle_start_date'])
    op.add_column('employee_payrolls', sa.Column('cycle_start_date', sa.Date(), nullable=False))
    op.add_column('employee_payrolls', sa.Column('cycle_end_date', sa.Date(), nullable=False))
    op.drop_index('ix_employee_payrolls_month', table_name='employee_payrolls')
    op.drop_index('ix_employee_payrolls_year', table_name='employee_payrolls')
    op.drop_constraint('uq_payroll_contract_month', 'employee_payrolls', type_='unique')
    op.create_index(op.f('ix_employee_payrolls_cycle_end_date'), 'employee_payrolls', ['cycle_end_date'], unique=False)
    op.create_index(op.f('ix_employee_payrolls_cycle_start_date'), 'employee_payrolls', ['cycle_start_date'], unique=False)
    op.create_unique_constraint('uq_payroll_contract_cycle_start', 'employee_payrolls', ['contract_id', 'cycle_start_date'])
    op.drop_column('employee_payrolls', 'year')
    op.drop_column('employee_payrolls', 'month')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('employee_payrolls', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('employee_payrolls', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_payroll_contract_cycle_start', 'employee_payrolls', type_='unique')
    op.drop_index(op.f('ix_employee_payrolls_cycle_start_date'), table_name='employee_payrolls')
    op.drop_index(op.f('ix_employee_payrolls_cycle_end_date'), table_name='employee_payrolls')
    op.create_unique_constraint('uq_payroll_contract_month', 'employee_payrolls', ['contract_id', 'year', 'month'])
    op.create_index('ix_employee_payrolls_year', 'employee_payrolls', ['year'], unique=False)
    op.create_index('ix_employee_payrolls_month', 'employee_payrolls', ['month'], unique=False)
    op.drop_column('employee_payrolls', 'cycle_end_date')
    op.drop_column('employee_payrolls', 'cycle_start_date')
    op.drop_constraint('uq_bill_contract_cycle_start', 'customer_bills', type_='unique')
    op.drop_index(op.f('ix_customer_bills_cycle_start_date'), table_name='customer_bills')
    op.drop_index(op.f('ix_customer_bills_cycle_end_date'), table_name='customer_bills')
    op.create_unique_constraint('uq_bill_contract_month', 'customer_bills', ['contract_id', 'year', 'month'])
    op.drop_column('customer_bills', 'cycle_end_date')
    op.drop_column('customer_bills', 'cycle_start_date')
    # ### end Alembic commands ###
