"""Add composite unique constraint to contract templates

Revision ID: db353738ea60
Revises: 609dd4616487
Create Date: 2025-11-13 23:03:08.088691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db353738ea60'
down_revision = '609dd4616487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.alter_column('template_name',
               existing_type=sa.VARCHAR(length=255),
               comment='模板名称',
               existing_comment='模板名称 (唯一)',
               existing_nullable=False)
        batch_op.drop_index('ix_contract_templates_template_name')
        batch_op.create_index(batch_op.f('ix_contract_templates_template_name'), ['template_name'], unique=False)
        batch_op.create_unique_constraint('uq_contract_template_name_version', ['template_name', 'version'])

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contract_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_contract_template_name_version', type_='unique')
        batch_op.drop_index(batch_op.f('ix_contract_templates_template_name'))
        batch_op.create_index('ix_contract_templates_template_name', ['template_name'], unique=True)
        batch_op.alter_column('template_name',
               existing_type=sa.VARCHAR(length=255),
               comment='模板名称 (唯一)',
               existing_comment='模板名称',
               existing_nullable=False)

    # ### end Alembic commands ###
