"""Add polymorphic association to BankTransaction

Revision ID: def6e5037fe6
Revises: f182902ccbd7
Create Date: 2025-10-15 09:22:09.095957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def6e5037fe6'
down_revision = 'f182902ccbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_object_type', sa.String(length=50), nullable=True, comment="关联对象的模型名称 (e.g., 'Contract', 'User', 'ServicePersonnel')"))
        batch_op.add_column(sa.Column('associated_object_id', sa.UUID(), nullable=True, comment='关联对象的主键ID'))
        batch_op.create_index('idx_bank_transactions_associated_object', ['associated_object_type', 'associated_object_id'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey1', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bank_transactions', schema=None) as batch_op:
        batch_op.drop_index('idx_bank_transactions_associated_object')
        batch_op.drop_column('associated_object_id')
        batch_op.drop_column('associated_object_type')

    # ### end Alembic commands ###
