"""Add cycle dates to bills and payrolls for uniqueness

Revision ID: e083cc28df75
Revises: d6e7d1fe9717
Create Date: 2025-07-15 16:08:34.104668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e083cc28df75'
down_revision = 'd6e7d1fe9717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_bills', 'cycle_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('customer_bills', 'cycle_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_customer_bills_cycle_end_date', table_name='customer_bills')
    op.drop_constraint('uq_bill_contract_cycle_start', 'customer_bills', type_='unique')
    op.add_column('employee_payrolls', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('employee_payrolls', sa.Column('month', sa.Integer(), nullable=False))
    op.alter_column('employee_payrolls', 'cycle_start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employee_payrolls', 'cycle_end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_index('ix_employee_payrolls_cycle_end_date', table_name='employee_payrolls')
    op.drop_constraint('uq_payroll_contract_cycle_start', 'employee_payrolls', type_='unique')
    op.create_index(op.f('ix_employee_payrolls_month'), 'employee_payrolls', ['month'], unique=False)
    op.create_index(op.f('ix_employee_payrolls_year'), 'employee_payrolls', ['year'], unique=False)
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employee_payrolls_year'), table_name='employee_payrolls')
    op.drop_index(op.f('ix_employee_payrolls_month'), table_name='employee_payrolls')
    op.create_unique_constraint('uq_payroll_contract_cycle_start', 'employee_payrolls', ['contract_id', 'cycle_start_date'])
    op.create_index('ix_employee_payrolls_cycle_end_date', 'employee_payrolls', ['cycle_end_date'], unique=False)
    op.alter_column('employee_payrolls', 'cycle_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employee_payrolls', 'cycle_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('employee_payrolls', 'month')
    op.drop_column('employee_payrolls', 'year')
    op.create_unique_constraint('uq_bill_contract_cycle_start', 'customer_bills', ['contract_id', 'cycle_start_date'])
    op.create_index('ix_customer_bills_cycle_end_date', 'customer_bills', ['cycle_end_date'], unique=False)
    op.alter_column('customer_bills', 'cycle_end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('customer_bills', 'cycle_start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
