"""Update precision for actual_work_days and overtime_days

Revision ID: e564b0d9f41d
Revises: 0345aa94a123
Create Date: 2025-10-20 17:15:48.144813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e564b0d9f41d'
down_revision = '0345aa94a123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('overtime_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='非节假日加班天数',
               existing_nullable=True)

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='实际劳务天数',
               existing_nullable=True)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey2', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_course_id_fkey2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.alter_column('overtime_days',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Numeric(precision=10, scale=3),
               existing_comment='替班期间的加班天数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('substitute_records', schema=None) as batch_op:
        batch_op.alter_column('overtime_days',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_comment='替班期间的加班天数',
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey2', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey2', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('employee_payrolls', schema=None) as batch_op:
        batch_op.alter_column('actual_work_days',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='实际劳务天数',
               existing_nullable=True)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('overtime_days',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_comment='非节假日加班天数',
               existing_nullable=True)

    # ### end Alembic commands ###
