"""uppercase_signing_status

Revision ID: e63dc675a8a9
Revises: 13b5e7655bde
Create Date: 2025-11-06 10:36:08.917588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e63dc675a8a9'
down_revision = '13b5e7655bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE contracts SET signing_status = 'UNSIGNED' WHERE signing_status = 'unsigned'")
    op.execute("UPDATE contracts SET signing_status = 'SIGNED' WHERE signing_status = 'signed'")
    op.execute("UPDATE contracts SET signing_status = 'PENDING' WHERE signing_status = 'pending'")
    op.execute("UPDATE contracts SET signing_status = 'CUSTOMER_SIGNED' WHERE signing_status = 'customer_signed'")
    op.execute("UPDATE contracts SET signing_status = 'EMPLOYEE_SIGNED' WHERE signing_status = 'employee_signed'")
    op.execute("UPDATE contracts SET signing_status = 'ACTIVE' WHERE signing_status = 'active'")
    op.execute("UPDATE contracts SET signing_status = 'TERMINATED' WHERE signing_status = 'terminated'")
    op.execute("UPDATE contracts SET signing_status = 'EXPIRED' WHERE signing_status = 'expired'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE contracts SET signing_status = 'unsigned' WHERE signing_status = 'UNSIGNED'")
    op.execute("UPDATE contracts SET signing_status = 'signed' WHERE signing_status = 'SIGNED'")
    op.execute("UPDATE contracts SET signing_status = 'pending' WHERE signing_status = 'PENDING'")
    op.execute("UPDATE contracts SET signing_status = 'customer_signed' WHERE signing_status = 'CUSTOMER_SIGNED'")
    op.execute("UPDATE contracts SET signing_status = 'employee_signed' WHERE signing_status = 'EMPLOYEE_SIGNED'")
    op.execute("UPDATE contracts SET signing_status = 'active' WHERE signing_status = 'ACTIVE'")
    op.execute("UPDATE contracts SET signing_status = 'terminated' WHERE signing_status = 'TERMINATED'")
    op.execute("UPDATE contracts SET signing_status = 'expired' WHERE signing_status = 'EXPIRED'")
    # ### end Alembic commands ###
