"""remove_unique_constraint_from_employee_access_token

Revision ID: e8ae03fe957b
Revises: 05012e09dfd4
Create Date: 2025-12-22 14:31:21.952348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ae03fe957b'
down_revision = '05012e09dfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_forms', schema=None) as batch_op:
        batch_op.drop_index('ix_attendance_forms_employee_access_token')
        batch_op.create_index(batch_op.f('ix_attendance_forms_employee_access_token'), ['employee_access_token'], unique=False)

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey1', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey1', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('attendance_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_forms_employee_access_token'))
        batch_op.create_index('ix_attendance_forms_employee_access_token', ['employee_access_token'], unique=True)

    # ### end Alembic commands ###
