"""Sync database schema with current models

Revision ID: eae8107673d8
Revises: 89595a570adf
Create Date: 2025-04-21 14:29:12.686466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eae8107673d8'
down_revision = '89595a570adf'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('evaluation_item', schema=None) as batch_op:
        batch_op.create_primary_key('evaluation_item_pkey', ['id']) # 确保表名和列名正确


    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['question_id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_table_comment(
        existing_comment='参考答案表，存储题目的参考答案和解析'
    )

    with op.batch_alter_table('answerrecord', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='答题记录表，存储用户的答题信息'
    )

    with op.batch_alter_table('employee_self_evaluation_detail', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'employee_self_evaluation', ['evaluation_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'evaluation_item', ['item_id'], ['id'])

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        # ### 添加数据清理步骤 ###
        # 删除 evaluated_user_id 不存在于 user 表的 evaluation 记录
        # 注意：这里假设您要删除这些违规数据。如果您需要更新，SQL 语句会不同。
        # 这里使用了一个子查询来找到不在 user 表中的 ID。
        batch_op.execute(
            """
            DELETE FROM evaluation
            WHERE evaluated_user_id NOT IN (SELECT id FROM "user");
            """
            # 如果您只想删除那个特定的 UUID，可以使用：
            # """
            # DELETE FROM evaluation
            # WHERE evaluated_user_id = '3b62c56e-2f34-4a7c-ab2d-998cc1a90267';
            # """
        )
        # ### 清理步骤结束 ###

        batch_op.create_foreign_key(None, 'user', ['evaluated_user_id'], ['id']) # 现在添加外键


    with op.batch_alter_table('evaluation_category', schema=None) as batch_op:
        batch_op.drop_index('idx_evaluation_category_allow_manual_input')
        batch_op.create_foreign_key('evaluation_category_aspect_id_fkey', 'evaluation_aspect', ['aspect_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('evaluation_detail', schema=None) as batch_op:
        # ### 添加针对 evaluation_detail 的数据清理步骤 ###
        # 删除 evaluation_detail 中 evaluation_id 不存在于 evaluation 表的记录
        batch_op.execute(
            """
            DELETE FROM evaluation_detail
            WHERE evaluation_id NOT IN (SELECT id FROM evaluation);
            """
            # 如果您只删除那个特定的 UUID，可以使用：
            # """
            # DELETE FROM evaluation_detail
            # WHERE evaluation_id = '3a711666-11cf-4bfc-96ba-7fdee01a8c79';
            # """
        )
        # ### 清理步骤结束 ###
        batch_op.create_foreign_key(None, 'evaluation', ['evaluation_id'], ['id'], ondelete='CASCADE')
        # ### 添加针对 evaluation_detail.item_id 的数据清理步骤 ###
        # 删除 evaluation_detail 中 item_id 不存在于 evaluation_item 表的记录
        batch_op.execute(
            """
            DELETE FROM evaluation_detail
            WHERE item_id NOT IN (SELECT id FROM evaluation_item);
            """
            # 如果您只删除那个特定的 UUID，可以使用：
            # """
            # DELETE FROM evaluation_detail
            # WHERE item_id = '65f36f8b-dad9-4423-87a0-ef10f169b7d2';
            # """
        )
        # ### 清理步骤结束 ###
        batch_op.create_foreign_key(None, 'evaluation_item', ['item_id'], ['id'])

    
    


    with op.batch_alter_table('evaluation_manual_input', schema=None) as batch_op:
        batch_op.alter_column('evaluation_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联到 evaluation 表，表示是哪次评价',
               existing_nullable=False)
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联到 evaluation_category 表，表示是针对哪个类别的评价',
               existing_nullable=False)
        batch_op.alter_column('manual_input',
               existing_type=sa.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='手动输入的评价文本')
        batch_op.drop_index('idx_evaluation_manual_input_aspect_id')
        batch_op.drop_index('idx_evaluation_manual_input_evaluation_id')
        # ### 添加针对 evaluation_manual_input.category_id 的数据清理步骤 ###
        # 删除 evaluation_manual_input 中 category_id 不存在于 evaluation_category 表的记录
        batch_op.execute(
            """
            DELETE FROM evaluation_manual_input
            WHERE category_id NOT IN (SELECT id FROM evaluation_category);
            """
            # 如果您只删除那个特定的 UUID，可以使用：
            # """
            # DELETE FROM evaluation_manual_input
            # WHERE category_id = 'd25db3ea-908a-49fc-997e-e07bdcbd8c9b';
            # """
        )
        # ### 清理步骤结束 ###
        batch_op.create_foreign_key(None, 'evaluation_category', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_table_comment(
        existing_comment='存储针对评价类别的手动文字输入内容'
    )
        batch_op.drop_column('id')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key('exam_user_id_fkey', 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint('exampapercourse_course_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('exampapercourse_exam_paper_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exampaperquestion', schema=None) as batch_op:
        batch_op.create_table_comment(
        '试卷题目关联表，存储试卷和题目的多对多关系及元数据',
        existing_comment='试卷题目关联表，存储试卷和题目的多对多关系'
    )

    with op.batch_alter_table('temp_answer_record', schema=None) as batch_op:
        batch_op.create_foreign_key('temp_answer_record_question_id_fkey', 'question', ['question_id'], ['id'])
        # ### 添加针对 temp_answer_record.user_id 的数据清理步骤 ###
        # 删除 temp_answer_record 中 user_id 不存在于 user 表的记录
        batch_op.execute(
            """
            DELETE FROM temp_answer_record
            WHERE user_id NOT IN (SELECT id FROM "user");
            """
            # 如果您只删除那个特定的 UUID，可以使用：
            # """
            # DELETE FROM temp_answer_record
            # WHERE user_id = '48bdab7a-7e56-4f4a-94d0-0563aea7aac3';
            # """
        )
        # ### 清理步骤结束 ###
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('temp_answer_record_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temp_answer_record', schema=None) as batch_op:
        batch_op.drop_constraint('temp_answer_record_exam_paper_id_fkey', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('temp_answer_record_question_id_fkey', type_='foreignkey')

    with op.batch_alter_table('exampaperquestion', schema=None) as batch_op:
        batch_op.create_table_comment(
        '试卷题目关联表，存储试卷和题目的多对多关系',
        existing_comment='试卷题目关联表，存储试卷和题目的多对多关系及元数据'
    )

    with op.batch_alter_table('exampapercourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('exampapercourse_course_id_fkey', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_constraint('exam_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_manual_input', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
        batch_op.create_table_comment(
        '存储针对评价类别的手动文字输入内容',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_evaluation_manual_input_evaluation_id', ['evaluation_id'], unique=False)
        batch_op.create_index('idx_evaluation_manual_input_aspect_id', ['category_id'], unique=False)
        batch_op.alter_column('manual_input',
               existing_type=sa.TEXT(),
               nullable=False,
               comment='手动输入的评价文本')
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               comment='关联到 evaluation_category 表，表示是针对哪个类别的评价',
               existing_nullable=False)
        batch_op.alter_column('evaluation_id',
               existing_type=sa.UUID(),
               comment='关联到 evaluation 表，表示是哪次评价',
               existing_nullable=False)

    with op.batch_alter_table('evaluation_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('evaluation_category', schema=None) as batch_op:
        batch_op.drop_constraint('evaluation_category_aspect_id_fkey', type_='foreignkey')
        batch_op.create_index('idx_evaluation_category_allow_manual_input', ['allow_manual_input'], unique=False)

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('employee_self_evaluation_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answerrecord', schema=None) as batch_op:
        batch_op.create_table_comment(
        '答题记录表，存储用户的答题信息',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.create_table_comment(
        '参考答案表，存储题目的参考答案和解析',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
