"""add_video_processs

Revision ID: f278973e3574
Revises: 708fb43ec328
Create Date: 2025-06-09 13:08:07.745247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f278973e3574'
down_revision = '708fb43ec328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_synthesis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('training_content_id', sa.UUID(), nullable=False),
    sa.Column('merged_audio_id', sa.UUID(), nullable=True),
    sa.Column('srt_file_path', sa.String(length=1024), nullable=True, comment='生成的SRT文件路径'),
    sa.Column('ppt_pdf_path', sa.String(length=1024), nullable=False, comment='用户上传的PPT导出的PDF文件路径'),
    sa.Column('llm_prompt_id', sa.UUID(), nullable=True),
    sa.Column('video_script_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='LLM生成的视频脚本JSON'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='合成状态 (pending_analysis, analysis_complete, synthesizing, complete, error)'),
    sa.Column('generated_resource_id', sa.UUID(), nullable=True, comment='最终生成的视频资源ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['generated_resource_id'], ['course_resource.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_prompt_id'], ['llm_prompts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_audio_id'], ['tts_audio.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['training_content_id'], ['training_content.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='视频合成任务表'
    )
    op.create_index(op.f('ix_video_synthesis_status'), 'video_synthesis', ['status'], unique=False)
    op.create_index(op.f('ix_video_synthesis_training_content_id'), 'video_synthesis', ['training_content_id'], unique=False)
    op.drop_constraint('exampapercourse_course_id_fkey', 'exampapercourse', type_='foreignkey')
    op.drop_constraint('exampapercourse_exam_paper_id_fkey', 'exampapercourse', type_='foreignkey')
    op.create_foreign_key(None, 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.create_foreign_key(None, 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'exampapercourse', schema='public', type_='foreignkey')
    op.create_foreign_key('exampapercourse_exam_paper_id_fkey', 'exampapercourse', 'exampaper', ['exam_paper_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exampapercourse_course_id_fkey', 'exampapercourse', 'trainingcourse', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_video_synthesis_training_content_id'), table_name='video_synthesis')
    op.drop_index(op.f('ix_video_synthesis_status'), table_name='video_synthesis')
    op.drop_table('video_synthesis')
    # ### end Alembic commands ###
